# Prepare and Load Data

## Load ipython-sql and connect to database

In [1]:
%load_ext sql

In [2]:
import os, re
from IPython.display import display_html

CONNECTION_STRING = os.getenv('AWSGPDBCONN')

cs = re.match('^postgresql:\/\/(\S+):(\S+)@(\S+):(\S+)\/(\S+)$', CONNECTION_STRING)

DB_USER   = cs.group(1)
DB_PWD    = cs.group(2)
DB_SERVER = cs.group(3)
DB_PORT   = cs.group(4)
DB_NAME   = cs.group(5)

%reload_ext sql
%sql $CONNECTION_STRING

'Connected: gpadmin@gpadmin'

In [3]:
#%sql postgresql://gpadmin:4Mk1FilwmKzZc@ec2-3-8-120-250.eu-west-2.compute.amazonaws.com:5432/gpadmin

In [4]:
%sql SELECT VERSION();

 * postgresql://gpadmin:***@ec2-35-178-108-225.eu-west-2.compute.amazonaws.com:5432/gpadmin
1 rows affected.

[('PostgreSQL 9.4.24 (Greenplum Database 6.3.0 build commit:77aa1b6e4486adbaede9f5f2864a04fc3a512e93) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Jan  9 2020 23:10:47',)]

In [5]:
%sql DROP SCHEMA pricing CASCADE;
%sql CREATE SCHEMA pricing;

 * postgresql://gpadmin:***@ec2-35-178-108-225.eu-west-2.compute.amazonaws.com:5432/gpadmin
(psycopg2.ProgrammingError) schema "pricing" does not exist

[SQL: DROP SCHEMA pricing CASCADE;]
(Background on this error at: http://sqlalche.me/e/f405)
 * postgresql://gpadmin:***@ec2-35-178-108-225.eu-west-2.compute.amazonaws.com:5432/gpadmin
Done.

[]

In [6]:
%sql SET search_path=pricing, public;

 * postgresql://gpadmin:***@ec2-35-178-108-225.eu-west-2.compute.amazonaws.com:5432/gpadmin
Done.

[]

## Create and load tables
### 1_Create_Airports

In [7]:
%%sql 
DROP TABLE IF EXISTS pricing.airports CASCADE;

CREATE TABLE pricing.airports (
    City TEXT,
    FAA VARCHAR(3),
    IATA VARCHAR(3),
    ICA VARCHAR(4),
    Airport TEXT,
    Airport_Role VARCHAR(3),
    Enplanements BIGINT,
    Hub_Assignment VARCHAR(3),
    is_hub INTEGER, 
    lat FLOAT,
    long FLOAT)
DISTRIBUTED BY(FAA);

INSERT INTO pricing.airports
    (city, faa, iata, ica, airport, airport_role, enplanements, hub_assignment, is_hub, lat, long) 
VALUES
	('Allentown', 'ABE', 'ABE', 'KABE', 'Lehigh Valley International Airport', 'P-S', 392039, 'MIA', 0, 40.6518559, -75.43499419999999), 
	('Abilene', 'ABI', 'ABI', 'KABI', 'Abilene Regional Airport', 'P-N', 73605, NULL, 0, 32.4118941, -99.6800464), 
	('Albuquerque', 'ABQ', 'ABQ', 'KABQ', 'Albuquerque International Sunport', 'P-M', 3158971, 'DFW', 0, 35.0433333, -106.6129085), 
	('Aberdeen', 'ABR', 'ABR', 'KABR', 'Aberdeen Regional Airport', 'P-N', 23225, NULL, 0, 45.4534583, -98.4177261), 
	('Albany', 'ABY', 'ABY', 'KABY', 'Southwest Georgia Regional Airport', 'P-N', 39200, NULL, 0, 31.53567109999999, -84.19390489999999), 
	('Nantucket', 'ACK', 'ACK', 'KACK', 'Nantucket Memorial Airport', 'P-N', 258214, NULL, 0, 41.2569516, -70.0637506), 
	('Waco', 'ACT', 'ACT', 'KACT', 'Waco Regional Airport', 'P-N', 61401, NULL, 0, 31.6135899, -97.2262908), 
	('Arcata/Eureka', 'ACV', 'ACV', 'KACV', 'Arcata Airport', 'P-N', 106637, NULL, 0, 40.9709197, -124.1065825), 
	('Atlantic City', 'ACY', 'ACY', 'KACY', 'Atlantic City International Airport', 'P-S', 527873, 'JFK', 0, 39.4515696, -74.57388499999999), 
	('Kodiak', 'ADQ', 'ADQ', 'PADQ', 'Kodiak Airport', 'P-N', 82057, NULL, 0, 57.7543254, -152.516958), 
	('Alexandria', 'AEX', 'AEX', 'KAEX', 'Alexandria International Airport', 'P-N', 179129, NULL, 0, 31.3274112, -92.5451856), 
	('Augusta', 'AGS', 'AGS', 'KAGS', 'Augusta Regional Airport at Bush Field', 'P-N', 176097, NULL, 0, 33.3688534, -81.9657651), 
	('King Salmon', 'AKN', 'AKN', 'PAKN', 'King Salmon Airport', 'P-N', 42310, NULL, 0, 58.67666699999999, -156.649167), 
	('Albany', 'ALB', 'ALB', 'KALB', 'Albany International Airport', 'P-S', 1365854, 'JFK', 0, 42.7487124, -73.8054981), 
	('Waterloo', 'ALO', 'ALO', 'KALO', 'Waterloo Regional Airport', 'P-N', 26831, NULL, 0, 42.5552262, -92.3979652), 
	('Walla Walla', 'ALW', 'ALW', 'KALW', 'Walla Walla Regional Airport', 'P-N', 29672, NULL, 0, 46.0873172, -118.2844589), 
	('Amarillo', 'AMA', 'AMA', 'KAMA', 'Rick Husband Amarillo International Airport', 'P-S', 394593, 'DFW', 0, 35.2203245, -101.7074509), 
	('Anchorage', 'ANC', 'ANC', 'PANC', 'Ted Stevens Anchorage International Airport', 'P-M', 2599313, 'LAX', 0, 61.17588629999999, -149.9900792), 
	('Aniak', 'ANI', 'ANI', 'PANI', 'Aniak Airport', 'P-N', 18526, NULL, 0, 61.5787947, -159.5345762), 
	('Aspen', 'ASE', 'ASE', 'KASE', 'Aspen-Pitkin County Airport (Sardy Field)', 'P-N', 213381, NULL, 0, 39.2196304, -106.8643335), 
	('Atlanta', 'ATL', 'ATL', 'KATL', 'Hartsfield-Jackson Atlanta International Airport', 'P-L', 43761280, 'MIA', 0, 33.6407282, -84.4277001), 
	('Appleton', 'ATW', 'ATW', 'KATW', 'Outagamie County Regional Airport', 'P-N', 259340, NULL, 0, 44.2602346, -88.5112347), 
	('Austin', 'AUS', 'AUS', 'KAUS', 'Austin-Bergstrom International Airport', 'P-M', 4201136, 'DFW', 0, 30.19747109999999, -97.66635289999999), 
	('Asheville', 'AVL', 'AVL', 'KAVL', 'Asheville Regional Airport', 'P-N', 682306, NULL, 0, 35.4348962, -82.53785409999999), 
	('Wilkes-Barre/Scranton', 'AVP', 'AVP', 'KAVP', 'Wilkes-Barre/Scranton International Airport', 'P-N', 219745, NULL, 0, 41.3377679, -75.7237811), 
	('Kalamazoo/Battle Creek', 'AZO', 'AZO', 'KAZO', 'Kalamazoo/Battle Creek International Airport', 'P-N', 168687, NULL, 0, 42.2355515, -85.5515933), 
	('Windsor Locks', 'BDL', 'BDL', 'KBDL', 'Bradley International Airport', 'P-M', 3006362, 'MIA', 0, 41.9388735, -72.68603139999999), 
	('Bethel', 'BET', 'BET', 'PABE', 'Bethel Airport', 'P-N', 140291, NULL, 0, 60.77972200000001, -161.8377779), 
	('Scottsbluff', 'BFF', 'BFF', 'KBFF', 'Western Nebraska Regional Airport (William B. Heilig Field)', 'P-N', 9221, NULL, 0, 41.8695184, -103.5934309), 
	('Seattle', 'BFI', 'BFI', 'KBFI', 'King County International Airport (Boeing Field)', 'P-N', 34597, NULL, 0, 47.5281657, -122.3018264), 
	('Bakersfield', 'BFL', 'BFL', 'KBFL', 'Meadows Field', 'P-N', 141847, NULL, 0, 35.4335053, -119.05622), 
	('Binghamton', 'BGM', 'BGM', 'KBGM', 'Greater Binghamton Airport (Edwin A. Link Field)', 'P-N', 125368, NULL, 0, 42.208651, -75.9813976), 
	('Bangor', 'BGR', 'BGR', 'KBGR', 'Bangor International Airport', 'P-S', 355508, 'ORD', 0, 44.808176, -68.8165035), 
	('Bar Harbor', 'BHB', 'BHB', 'KBHB', 'Hancock County-Bar Harbor Airport', 'P-N', 10562, NULL, 0, 44.4450987, -68.3621263), 
	('Birmingham', 'BHM', 'BHM', 'KBHM', 'Birmingham-Shuttlesworth International Airport', 'P-S', 1443215, 'DFW', 0, 33.5624269, -86.754126), 
	('Billings', 'BIL', 'BIL', 'KBIL', 'Billings Logan International Airport', 'P-S', 422494, 'JFK', 0, 41.9388735, -72.68603139999999), 
	('Bismarck', 'BIS', 'BIS', 'KBIS', 'Bismarck Municipal Airport', 'P-N', 178005, NULL, 0, 46.77518999999999, -100.7572447), 
	('Bemidji', 'BJI', 'BJI', 'KBJI', 'Bemidji Regional Airport', 'P-N', 22007, NULL, 0, 47.5092442, -94.9329041), 
	('Boulder City', 'BVU', 'BLD', 'KBVU', 'Boulder City Municipal Airport', 'P-N', 300553, NULL, 0, 41.9388735, -72.68603139999999), 
	('Bellingham', 'BLI', 'BLI', 'KBLI', 'Bellingham International Airport', 'P-N', 277281, NULL, 0, 48.7955792, -122.5330642), 
	('Belleville', 'BLV', 'BLV', 'KBLV', 'MidAmerica St. Louis Airport/Scott Air Force Base', 'P-N', 27002, NULL, 0, 38.5491996, -89.8216405), 
	('Bloomington/Normal', 'BMI', 'BMI', 'KBMI', 'Central Illinois Regional Airport at Bloomington-Normal', 'P-N', 262846, NULL, 0, 40.4801853, -88.9189342), 
	('Nashville', 'BNA', 'BNA', 'KBNA', 'Nashville International Airport (Berry Field)', 'P-M', 4648000, 'ORD', 0, 36.126317, -86.67737129999999), 
	('Boise', 'BOI', 'BOI', 'KBOI', 'Boise Airport (Boise Air Terminal) (Gowen Field)', 'P-S', 1574210, 'ORD', 0, 43.5658231, -116.2223159), 
	('Boston', 'BOS', 'BOS', 'KBOS', 'Gen. Edward Lawrence Logan International Airport', 'P-L', 12820489, 'JFK', 0, 42.3656132, -71.0095602), 
	('Beaumont/Port Arthur', 'BPT', 'BPT', 'KBPT', 'Southeast Texas Regional Airport', 'P-N', 17394, NULL, 0, 29.955847, -94.0220743), 
	('Brunswick', 'BQK', 'BQK', 'KBQK', 'Brunswick Golden Isles Airport', 'P-N', 29594, NULL, 0, 31.2548331, -81.46691109999999), 
	('Brainerd', 'BRD', 'BRD', 'KBRD', 'Brainerd Lakes Regional Airport', 'P-N', 16665, NULL, 0, 46.3930459, -94.1412635), 
	('Brownsville', 'BRO', 'BRO', 'KBRO', 'Brownsville/South Padre Island International Airport', 'P-N', 84401, NULL, 0, 25.9063266, -97.4269855), 
	('Barrow', 'BRW', 'BRW', 'PABR', 'Wiley Post-Will Rogers Memorial Airport', 'P-N', 40674, NULL, 0, 71.2874212, -156.7802701), 
	('Butte', 'BTM', 'BTM', 'KBTM', 'Bert Mooney Airport', 'P-N', 30431, NULL, 0, 45.9551935, -112.5021977), 
	('Baton Rouge', 'BTR', 'BTR', 'KBTR', 'Baton Rouge Metropolitan Airport (Ryan Field)', 'P-S', 382687, 'MIA', 0, 30.5323599, -91.15146100000001), 
	('Burlington', 'BTV', 'BTV', 'KBTV', 'Burlington International Airport', 'P-S', 747559, 'JFK', 0, 44.4706939, -73.1516037), 
	('Buffalo', 'BUF', 'BUF', 'KBUF', 'Buffalo Niagara International Airport', 'P-M', 2744501, 'JFK', 0, 42.9397059, -78.7295067), 
	('Burbank', 'BUR', 'BUR', 'KBUR', 'Bob Hope Airport', 'P-M', 2647287, 'LAX', 0, 34.1983122, -118.3574036), 
	('Baltimore/Glen Burnie', 'BWI', 'BWI', 'KBWI', 'Baltimore/Washington International Thurgood Marshall Airport', 'P-L', 10215225, 'ORD', 0, 39.1774042, -76.6683922), 
	('Bozeman', 'BZN', 'BZN', 'KBZN', 'Gallatin Field Airport', 'P-N', 349550, NULL, 0, 45.7771073, -111.1532346), 
	('Columbia', 'CAE', 'CAE', 'KCAE', 'Columbia Metropolitan Airport', 'P-S', 565938, 'ORD', 0, 33.941917, -81.1220015), 
	('Akron', 'CAK', 'CAK', 'KCAK', 'Akron-Canton Regional Airport', 'P-S', 715367, 'JFK', 0, 40.9153779, -81.4418833), 
	('Cordova', 'CDV', 'CDV', 'PACV', 'Merle K. (Mudhole) Smith Airport', 'P-N', 16640, NULL, 0, 60.4934354, -145.4757287), 
	('Crescent City', 'CEC', 'CEC', 'KCEC', 'Del Norte County Airport (Jack McNamara Field)', 'P-N', 12541, NULL, 0, 41.7747891, -124.2371456), 
	('Chattanooga', 'CHA', 'CHA', 'KCHA', 'Chattanooga Metropolitan Airport (Lovell Field)', 'P-N', 300796, NULL, 0, 35.0374486, -85.19701119999999), 
	('Charlottesville', 'CHO', 'CHO', 'KCHO', 'Charlottesville-Albemarle Airport', 'P-N', 169843, NULL, 0, 38.1394877, -78.4516149), 
	('Charleston', 'CHS', 'CHS', 'KCHS', 'Charleston International Airport/Charleston AFB', 'P-S', 1174667, 'ORD', 0, 32.8942676, -80.038159), 
	('Chico', 'CIC', 'CIC', 'KCIC', 'Chico Municipal Airport', 'P-N', 24809, NULL, 0, 39.7990801, -121.8548167), 
	('Cedar Rapids', 'CID', 'CID', 'KCID', 'The Eastern Iowa Airport', 'P-S', 499600, 'ORD', 0, 41.8863861, -91.70697539999999), 
	('Sault Ste. Marie', 'CIU', 'CIU', 'KCIU', 'Chippewa County International Airport', 'P-N', 13269, NULL, 0, 46.2577577, -84.4744174), 
	('Carlsbad', 'CRQ', 'CLD', 'KCRQ', 'McClellan-Palomar Airport', 'P-N', 35033, NULL, 0, 33.1268216, -117.2792408), 
	('Cleveland', 'CLE', 'CLE', 'KCLE', 'Cleveland-Hopkins International Airport', 'P-M', 4704329, 'DWF', 0, 41.4057985, -81.8538669), 
	('College Station', 'CLL', 'CLL', 'KCLL', 'Easterwood Airport (Easterwood Field)', 'P-N', 72188, NULL, 0, 30.5936801, -96.36660529999999), 
	('Port Angeles', 'CLM', 'CLM', 'KCLM', 'William R. Fairchild International Airport', 'P-N', 12672, NULL, 0, 26.0742344, -80.1506022), 
	('Charlotte', 'CLT', 'CLT', 'KCLT', 'Charlotte/Douglas International Airport', 'P-L', 18281425, 'JFK', 0, 35.2144026, -80.9473146), 
	('Columbus', 'CMH', 'CMH', 'KCMH', 'Port Columbus International Airport', 'P-M', 3096515, 'JFK', 0, 39.9999399, -82.8871767), 
	('Champaign/Urbana', 'CMI', 'CMI', 'KCMI', 'University of Illinois - Willard Airport', 'P-N', 98225, NULL, 0, 40.03649619999999, -88.26398789999999), 
	('Hancock/Calumet', 'CMX', 'CMX', 'KCMX', 'Houghton County Memorial Airport', 'P-N', 25354, NULL, 0, 47.16870429999999, -88.4941169), 
	('Cody', 'COD', 'COD', 'KCOD', 'Yellowstone Regional Airport', 'P-N', 25863, NULL, 0, 44.520442, -109.0225794), 
	('Colorado Springs', 'COS', 'COS', 'KCOS', 'City of Colorado Springs Municipal Airport', 'P-S', 997348, 'ORD', 0, 38.801712, -104.7026039), 
	('Columbia', 'COU', 'COU', 'KCOU', 'Columbia Regional Airport', 'P-N', 12719, NULL, 0, 38.8155232, -92.2193772), 
	('Casper', 'CPR', 'CPR', 'KCPR', 'Casper/Natrona County International Airport', 'P-N', 74167, NULL, 0, 42.89727509999999, -106.4648786), 
	('Corpus Christi/Kingsville', 'CRP', 'CRP', 'KCRP', 'Corpus Christi International Airport', 'P-N', 339193, NULL, 0, 27.7724235, -97.5021829), 
	('Charleston', 'CRW', 'CRW', 'KCRW', 'Yeager Airport', 'P-N', 243793, NULL, 0, 38.3714489, -81.5934922), 
	('Columbus', 'CSG', 'CSG', 'KCSG', 'Columbus Airport', 'P-N', 51288, NULL, 0, 32.5143625, -84.9410549), 
	('Covington', 'CVG', 'CVG', 'KCVG', 'Cincinnati/Northern Kentucky International Airport', 'P-L', 5194214, 'ORD', 0, 39.0532746, -84.6630165), 
	('Charlevoix', 'CVX', 'CVX', 'KCVX', 'Charlevoix Municipal Airport', 'P-N', 17854, NULL, 0, 45.3047915, -85.2759218), 
	('Mosinee', 'CWA', 'CWA', 'KCWA', 'Central Wisconsin Airport', 'P-N', 154312, NULL, 0, 44.784201, -89.67268), 
	('Cheyenne', 'CYS', 'CYS', 'KCYS', 'Cheyenne Regional Airport (Jerry Olson Field)', 'P-N', 16697, NULL, 0, 41.15298629999999, -104.810231), 
	('Daytona Beach', 'DAB', 'DAB', 'KDAB', 'Daytona Beach International Airport', 'P-N', 282784, NULL, 0, 29.1832134, -81.0532273), 
	('Dallas', 'DAL', 'DAL', 'KDAL', 'Dallas Love Field', 'P-M', 3783407, 'DFW', 0, 32.8481029, -96.8512063), 
	('Dayton', 'DAY', 'DAY', 'KDAY', 'James M. Cox Dayton International Airport', 'P-S', 1240848, 'MIA', 0, 39.90252419999999, -84.2217719), 
	('Dubuque', 'DBQ', 'DBQ', 'KDBQ', 'Dubuque Regional Airport', 'P-N', 42870, NULL, 0, 42.3972121, -90.7057047), 
	('Washington D.C. (Arlington County)', 'DCA', 'DCA', 'KDCA', 'Ronald Reagan Washington National Airport', 'P-L', 8704466, 'JFK', 0, 38.851242, -77.04023149999999), 
	('Denver', 'DEN', 'DEN', 'KDEN', 'Denver International Airport', 'P-L', 24287939, 'DFW', 0, 39.8560963, -104.6737376), 
	('Dallas-Fort Worth', 'DFW', 'DFW', 'KDFW', 'Dallas-Fort Worth International Airport', 'P-L', 27100656, NULL, 1, 32.8998091, -97.0403352), 
	('Dothan', 'DHN', 'DHN', 'KDHN', 'Dothan Regional Airport', 'P-N', 41453, NULL, 0, 31.3148738, -85.44872099999999), 
	('Dillingham', 'DLG', 'DLG', 'PADL', 'Dillingham Airport', 'P-N', 32215, NULL, 0, 59.0420062, -158.508371), 
	('Duluth', 'DLH', 'DLH', 'KDLH', 'Duluth International Airport', 'P-N', 147793, NULL, 0, 46.8387531, -92.1800102), 
	('Durango', 'DRO', 'DRO', 'KDRO', 'Durango-La Plata County Airport', 'P-N', 134386, NULL, 0, 37.1506067, -107.7532559), 
	('Del Rio', 'DRT', 'DRT', 'KDRT', 'Del Rio International Airport', 'P-N', 13180, NULL, 0, 29.3705861, -100.920213), 
	('Des Moines', 'DSM', 'DSM', 'KDSM', 'Des Moines International Airport', 'P-S', 919990, 'ORD', 0, 41.5341333, -93.6587958), 
	('Detroit/Romulus', 'DTW', 'DTW', 'KDTW', 'Detroit Metropolitan Wayne County Airport', 'P-L', 16998174, 'ORD', 0, 42.2161722, -83.3553842), 
	('Unalaska', 'DUT', 'DUT', 'PADU', 'Unalaska Airport (Tom Madsen Airport)', 'P-N', 28234, NULL, 0, 53.8983407, -166.5442157), 
	('Wenatchee', 'EAT', 'EAT', 'KEAT', 'Pangborn Memorial Airport', 'P-N', 48275, NULL, 0, 47.398951, -120.206495), 
	('Eau Claire', 'EAU', 'EAU', 'KEAU', 'Chippewa Valley Regional Airport', 'P-N', 18762, NULL, 0, 44.8622211, -91.48222190000001), 
	('Eagle', 'EGE', 'EGE', 'KEGE', 'Eagle County Regional Airport', 'P-N', 212832, NULL, 0, 39.6425637, -106.9145481), 
	('Elko', 'EKO', 'EKO', 'KEKO', 'Elko Regional Airport (J.C. Harris Field)', 'P-N', 25523, NULL, 0, 40.8278188, -115.786212), 
	('Elmira/Corning', 'ELM', 'ELM', 'KELM', 'Elmira/Corning Regional Airport', 'P-N', 104508, NULL, 0, 42.1604316, -76.8921794), 
	('El Paso', 'ELP', 'ELP', 'KELP', 'El Paso International Airport', 'P-S', 1509093, 'DFW', 0, 31.8053354, -106.3824345), 
	('Kenai', 'ENA', 'ENA', 'PAEN', 'Kenai Municipal Airport', 'P-N', 96565, NULL, 0, 60.57054540000001, -151.2461827), 
	('Erie', 'ERI', 'ERI', 'KERI', 'Erie International Airport (Tom Ridge Field)', 'P-N', 124667, NULL, 0, 42.0840391, -80.1719311), 
	('Eugene', 'EUG', 'EUG', 'KEUG', 'Eugene Airport (Mahlon Sweet Field)', 'P-N', 358819, NULL, 0, 44.1217811, -123.2159003), 
	('Evansville', 'EVV', 'EVV', 'KEVV', 'Evansville Regional Airport', 'P-N', 193349, NULL, 0, 38.0433641, -87.52717539999999), 
	('New Bedford', 'EWB', 'EWB', 'KEWB', 'New Bedford Regional Airport', 'P-N', 13908, NULL, 0, 41.675297, -70.95818799999999), 
	('New Bern', 'EWN', 'EWN', 'KEWN', 'Coastal Carolina Regional Airport (was Craven Co. Regional)', 'P-N', 111184, NULL, 0, 35.0776455, -77.0382005), 
	('Newark', 'EWR', 'EWR', 'KEWR', 'Newark Liberty International Airport', 'P-L', 17599578, 'JFK', 0, 40.6895314, -74.1744624), 
	('Key West', 'EYW', 'EYW', 'KEYW', 'Key West International Airport', 'P-N', 231339, NULL, 0, 24.5536707, -81.7549737), 
	('Fairbanks', 'FAI', 'FAI', 'PAFA', 'Fairbanks International Airport', 'P-S', 456947, 'LAX', 0, 64.8164163, -147.8635168), 
	('Fargo', 'FAR', 'FAR', 'KFAR', 'Hector International Airport', 'P-N', 326941, NULL, 0, 46.9198612, -96.8255648), 
	('Fresno', 'FAT', 'FAT', 'KFAT', 'Fresno Yosemite International Airport', 'P-S', 600489, 'LAX', 0, 36.7758493, -119.7181083), 
	('Fayetteville', 'FAY', 'FAY', 'KFAY', 'Fayetteville Regional Airport (Grannis Field)', 'P-N', 202597, NULL, 0, 34.9910665, -78.887089), 
	('Kalispell', 'GPI', 'FCA', 'KGPI', 'Glacier Park International Airport', 'P-N', 186450, NULL, 0, 48.3076648, -114.2525337), 
	('Flagstaff', 'FLG', 'FLG', 'KFLG', 'Flagstaff Pulliam Airport', 'P-N', 51765, NULL, 0, 35.1401934, -111.6708808), 
	('Fort Lauderdale', 'FLL', 'FLL', 'KFLL', 'Fort Lauderdale-Hollywood International Airport', 'P-L', 11020091, 'MIA', 0, 26.0742344, -80.1506022), 
	('Florence', 'FLO', 'FLO', 'KFLO', 'Florence Regional Airport', 'P-N', 64835, NULL, 0, 34.1931906, -79.7281922), 
	('Farmington', 'FMN', 'FMN', 'KFMN', 'Four Corners Regional Airport', 'P-N', 17044, NULL, 0, 36.7386433, -108.2273), 
	('Fort Collins/Loveland', 'FNL', 'FNL', 'KFNL', 'Fort Collins-Loveland Municipal Airport', 'P-N', 31094, NULL, 0, 21.3245132, -157.9250736), 
	('Flint', 'FNT', 'FNT', 'KFNT', 'Bishop International Airport', 'P-S', 526492, 'LAX', 0, 42.9734164, -83.7388467), 
	('Friday Harbor', 'FHR', 'FRD', 'KFHR', 'Friday Harbor Airport', 'P-N', 13835, NULL, 0, 48.5248261, -123.0261849), 
	('Sioux Falls', 'FSD', 'FSD', 'KFSD', 'Sioux Falls Regional Airport (Joe Foss Field)', 'P-S', 367874, 'ORD', 0, 43.5828065, -96.7402171), 
	('Fort Smith', 'FSM', 'FSM', 'KFSM', 'Fort Smith Regional Airport', 'P-N', 85095, NULL, 0, 35.3380696, -94.3635085), 
	('Fort Wayne', 'FWA', 'FWA', 'KFWA', 'Fort Wayne International Airport', 'P-N', 282449, NULL, 0, 40.9828674, -85.18844229999999), 
	('Gillette', 'GCC', 'GCC', 'KGCC', 'Gillette-Campbell County Airport', 'P-N', 28232, NULL, 0, 44.348086, -105.5390962), 
	('Garden City', 'GCK', 'GCK', 'KGCK', 'Garden City Regional Airport', 'P-N', 11453, NULL, 0, 37.9268913, -100.7198703), 
	('Grand Canyon/Tusayan', 'GCN', 'GCN', 'KGCN', 'Grand Canyon National Park Airport', 'P-S', 294436, 'ORD', 0, 35.9526026, -112.1444184), 
	('Peach Springs', '1G4', 'GCW', NULL, 'Grand Canyon West Airport', 'P-N', 65351, NULL, 0, 35.9876807, -113.8206185), 
	('Spokane', 'GEG', 'GEG', 'KGEG', 'Spokane International Airport (Geiger Field)', 'P-S', 1691345, 'JFK', 0, 47.62174779999999, -117.534812), 
	('Grand Forks', 'GFK', 'GFK', 'KGFK', 'Grand Forks International Airport', 'P-N', 88093, NULL, 0, 47.942861, -97.176582), 
	('Longview', 'GGG', 'GGG', 'KGGG', 'East Texas Regional Airport', 'P-N', 21830, NULL, 0, 32.3876264, -94.71911860000002), 
	('Grand Junction', 'GJT', 'GJT', 'KGJT', 'Grand Junction Regional Airport (Walker Field)', 'P-N', 212588, NULL, 0, 39.1222307, -108.5291468), 
	('Gainesville', 'GNV', 'GNV', 'KGNV', 'Gainesville Regional Airport', 'P-N', 136623, NULL, 0, 29.6863121, -82.2766402), 
	('Gulfport/Biloxi', 'GPT', 'GPT', 'KGPT', 'Gulfport-Biloxi International Airport', 'P-S', 461072, 'MIA', 0, 30.4131137, -89.0727778), 
	('Green Bay', 'GRB', 'GRB', 'KGRB', 'Austin Straubel International Airport', 'P-S', 410348, 'JFK', 0, 44.4926999, -88.1271783), 
	('Grand Island', 'GRI', 'GRI', 'KGRI', 'Central Nebraska Regional Airport', 'P-N', 20136, NULL, 0, 40.9694381, -98.3129098), 
	('Fort Hood/Killeen/Temple', 'GRK', 'GRK', 'KGRK', 'Killeen-Fort Hood Regional Airport/Robert Gray Army Airfield', 'P-N', 243861, NULL, 0, 31.06138019999999, -97.8213287), 
	('Grand Rapids', 'GRR', 'GRR', 'KGRR', 'Gerald R. Ford International Airport', 'P-S', 902925, 'LAX', 0, 42.8846633, -85.5248434), 
	('Greensboro', 'GSO', 'GSO', 'KGSO', 'Piedmont Triad International Airport', 'P-S', 863745, 'JFK', 0, 36.1043671, -79.9351805), 
	('Greer', 'GSP', 'GSP', 'KGSP', 'Greenville-Spartanburg International Airport (Roger Milliken Field)', 'P-S', 699805, 'ORD', 0, 34.8959008, -82.2172338), 
	('Gustavus', 'GST', 'GST', 'PAGS', 'Gustavus Airport', 'P-N', 11828, NULL, 0, 58.422469, -135.7030421), 
	('Great Falls', 'GTF', 'GTF', 'KGTF', 'Great Falls International Airport', 'P-N', 143811, NULL, 0, 47.4825016, -111.3566299), 
	('Columbu/ West Point/Starkville', 'GTR', 'GTR', 'KGTR', 'Golden Triangle Regional Airport', 'P-N', 36329, NULL, 0, 33.4516041, -88.587603), 
	('Gunnison', 'GUC', 'GUC', 'KGUC', 'Gunnison-Crested Butte Regional Airport', 'P-N', 36035, NULL, 0, 38.5371548, -106.935603), 
	('Hayden', 'HDN', 'HDN', 'KHDN', 'Yampa Valley Airport (Yampa Valley Regional)', 'P-N', 136600, NULL, 0, 40.4826338, -107.2169065), 
	('Hilton Head Island', 'HXD', 'HHH', 'KHXD', 'Hilton Head Airport', 'P-N', 79912, NULL, 0, 32.2248476, -80.6971648), 
	('Helena', 'HLN', 'HLN', 'KHLN', 'Helena Regional Airport', 'P-N', 85649, NULL, 0, 46.6095791, -111.9902266), 
	('Honolulu', 'HNL', 'HNL', 'PHNL', 'Honolulu International Airport Hickam AFB', 'P-L', 9013440, 'LAX', 0, 21.3245132, -157.9250736), 
	('Homer', 'HOM', 'HOM', 'PAHO', 'Homer Airport', 'P-N', 44288, NULL, 0, 59.643151, -151.4928655), 
	('Houston', 'HOU', 'HOU', 'KHOU', 'William P. Hobby Airport', 'P-M', 4357835, 'DFW', 0, 29.6459077, -95.27690539999999), 
	('White Plains', 'HPN', 'HPN', 'KHPN', 'Westchester County Airport', 'P-S', 904482, 'JFK', 0, 41.0683325, -73.7086641), 
	('Harlingen', 'HRL', 'HRL', 'KHRL', 'Valley International Airport', 'P-S', 373438, 'DFW', 0, 26.2234764, -97.6623631), 
	('Huntsville', 'HSV', 'HSV', 'KHSV', 'Huntsville International Airport ("Carl T. Jones Field")', 'P-S', 606127, 'DFW', 0, 34.6403329, -86.77568989999999), 
	('Huntington', 'HTS', 'HTS', 'KHTS', 'Tri-State Airport (Milton J. Ferguson Field)', 'P-N', 83531, NULL, 0, 38.3683533, -82.5578085), 
	('New Haven', 'HVN', 'HVN', 'KHVN', 'Tweed New Haven Regional Airport', 'P-N', 33988, NULL, 0, 41.2678919, -72.8868727), 
	('Hyannis', 'HYA', 'HYA', 'KHYA', 'Barnstable Municipal Airport (Boardman/Polando Field)', 'P-N', 191906, NULL, 0, 41.6673379, -70.2847445), 
	('Washington D.C. (Chantilly/Dulles)', 'IAD', 'IAD', 'KIAD', 'Washington Dulles International Airport', 'P-L', 11348775, 'JFK', 0, 38.9531162, -77.45653879999999), 
	('Houston', 'IAH', 'IAH', 'KIAH', 'George Bush Intercontinental Airport', 'P-L', 19528627, 'DFW', 0, 29.9902199, -95.3367827), 
	('Wichita', 'ICT', 'ICT', 'KICT', 'Wichita Mid-Continent Airport', 'P-S', 780756, 'ORD', 0, 37.6508529, -97.42869879999999), 
	('Idaho Falls', 'IDA', 'IDA', 'KIDA', 'Idaho Falls Regional Airport (Fanning Field)', 'P-N', 148584, NULL, 0, 43.5152294, -112.0678843), 
	('Bullhead City', 'IFP', 'IFP', 'KIFP', 'Laughlin/Bullhead International Airport', 'P-N', 122192, NULL, 0, 35.1562931, -114.5584335), 
	('Wilmington', 'ILM', 'ILM', 'KILM', 'Wilmington International Airport', 'P-N', 469993, NULL, 0, 34.2668931, -77.91052010000001), 
	('Indianapolis', 'IND', 'IND', 'KIND', 'Indianapolis International Airport', 'P-M', 4061450, 'MIA', 0, 39.7168593, -86.2955952), 
	('International Falls', 'INL', 'INL', 'KINL', 'Falls International Airport', 'P-N', 16590, NULL, 0, 48.5663926, -93.397607), 
	('Williamsport', 'IPT', 'IPT', 'KIPT', 'Williamsport Regional Airport', 'P-N', 23901, NULL, 0, 41.245182, -76.91881000000001), 
	('Islip', 'ISP', 'ISP', 'KISP', 'Long Island MacArthur Airport', 'P-S', 1048768, 'JFK', 0, 40.7956189, -73.09880249999999), 
	('Ithaca', 'ITH', 'ITH', 'KITH', 'Ithaca Tompkins Regional Airport', 'P-N', 91866, NULL, 0, 42.4910812, -76.4584974), 
	('Hilo', 'ITO', 'ITO', 'PHTO', 'Hilo International Airport', 'P-S', 648263, 'LAX', 0, 19.7188342, -155.0416866), 
	('Inyokern', 'IYK', 'IYK', 'KIYK', 'Inyokern Airport', 'P-N', 11149, NULL, 0, 35.6525663, -117.8272962), 
	('Jackson', 'JAC', 'JAC', 'KJAC', 'Jackson Hole Airport', 'P-N', 305566, NULL, 0, 43.6084108, -110.7366517), 
	('Jackson', 'JAN', 'JAN', 'KJAN', 'Jackson-Evers International Airport', 'P-S', 618373, 'MIA', 0, 32.3122283, -90.0764217), 
	('Jacksonville', 'JAX', 'JAX', 'KJAX', 'Jacksonville International Airport', 'P-M', 2965973, 'MIA', 0, 30.49407129999999, -81.6879368), 
	('New York', 'JFK', 'JFK', 'KJFK', 'John F. Kennedy International Airport', 'P-L', 23620948, NULL, 1, 40.6413111, -73.77813909999999), 
	('Juneau', 'JNU', 'JNU', 'PAJN', 'Juneau International Airport', 'P-S', 378741, 'LAX', 0, 58.3579806, -134.5831791), 
	('Manokotak', 'MBA', 'KMO', 'PAMB', 'Manokotak Airport', 'P-N', 13393, NULL, 0, 58.9358015, -158.899002), 
	('Kailua/Kona', 'KOA', 'KOA', 'PHKO', 'Kona International Airport at Keahole', 'P-S', 1332667, 'LAX', 0, 19.736916, -156.0429246), 
	('Ketchikan', 'KTN', 'KTN', 'PAKT', 'Ketchikan International Airport', 'P-N', 108837, NULL, 0, 55.3554106, -131.7105604), 
	('Lansing', 'LAN', 'LAN', 'KLAN', 'Capital Region International Airport (was Lansing Capital City)', 'P-N', 217437, NULL, 0, 42.7751565, -84.5901729), 
	('Laramie', 'LAR', 'LAR', 'KLAR', 'Laramie Regional Airport', 'P-N', 10371, NULL, 0, 41.3201937, -105.6703447), 
	('Las Vegas', 'LAS', 'LAS', 'KLAS', 'McCarran International Airport', 'P-L', 21024443, 'DFW', 0, 36.0839998, -115.1537389), 
	('Lawton', 'LAW', 'LAW', 'KLAW', 'Lawton-Fort Sill Regional Airport', 'P-N', 77533, NULL, 0, 34.5726626, -98.4159133), 
	('Los Angeles', 'LAX', 'LAX', 'KLAX', 'Los Angeles International Airport', 'P-L', 28861477, NULL, 1, 33.9415889, -118.40853), 
	('Lubbock', 'LBB', 'LBB', 'KLBB', 'Lubbock Preston Smith International Airport', 'P-S', 508858, 'DFW', 0, 33.6565685, -101.8222599), 
	('Latrobe', 'LBE', 'LBE', 'KLBE', 'Arnold Palmer Regional Airport', 'P-N', 18946, NULL, 0, 40.2730644, -79.4082315), 
	('Lake Charles', 'LCH', 'LCH', 'KLCH', 'Lake Charles Regional Airport', 'P-N', 65340, NULL, 0, 30.1229972, -93.2211183), 
	('Lexington', 'LEX', 'LEX', 'KLEX', 'Blue Grass Airport', 'P-S', 450464, 'MIA', 0, 38.03776149999999, -84.6026083), 
	('Lafayette', 'LFT', 'LFT', 'KLFT', 'Lafayette Regional Airport', 'P-N', 220211, NULL, 0, 30.205482, -91.9894188), 
	('New York', 'LGA', 'LGA', 'KLGA', 'LaGuardia Airport (and Marine Air Terminal)', 'P-L', 11567586, 'ORD', 0, 40.7769271, -73.8739659), 
	('Long Beach', 'LGB', 'LGB', 'KLGB', 'Long Beach Airport (Daugherty Field)', 'P-S', 1413251, 'LAX', 0, 33.8176974, -118.1523845), 
	('Līhu\ʻe (Lihue)', 'LIH', 'LIH', 'PHLI', 'Līhu\ʻe Airport (Lihue Airport)', 'P-S', 1287696, 'LAX', 0, 21.9788489, -159.3437585), 
	('Little Rock', 'LIT', 'LIT', 'KLIT', 'Little Rock National Airport (Adams Field)', 'P-S', 1181846, 'ORD', 0, 34.7307049, -92.2216531), 
	('Klamath Falls', 'LMT', 'LMT', 'KLMT', 'Klamath Falls Airport (Kingsley Field)', 'P-N', 26970, NULL, 0, 42.16520269999999, -121.7463436), 
	('Lincoln', 'LNK', 'LNK', 'KLNK', 'Lincoln Airport (was Lincoln Municipal)', 'P-N', 142507, NULL, 0, 40.8506586, -96.7581014), 
	('Lanai City', 'LNY', 'LNY', 'PHNY', 'Lanai Airport', 'P-N', 52075, NULL, 0, 20.785386, -156.9513273), 
	('Laredo', 'LRD', 'LRD', 'KLRD', 'Laredo International Airport', 'P-N', 112520, NULL, 0, 27.5447829, -99.4613589), 
	('La Crosse', 'LSE', 'LSE', 'KLSE', 'La Crosse Municipal Airport', 'P-N', 111462, NULL, 0, 43.8753591, -91.2634558), 
	('Lewiston', 'LWS', 'LWS', 'KLWS', 'Lewiston-Nez Perce County Airport', 'P-N', 64379, NULL, 0, 46.3740418, -117.014737), 
	('Lynchburg', 'LYH', 'LYH', 'KLYH', 'Lynchburg Regional Airport (Preston Glenn Field)', 'P-N', 55307, NULL, 0, 37.3271839, -79.2002065), 
	('Midland', 'MAF', 'MAF', 'KMAF', 'Midland International Airport', 'P-S', 445043, 'JFK', 0, 31.9417386, -102.2047497), 
	('Saginaw', 'MBS', 'MBS', 'KMBS', 'MBS International Airport', 'P-N', 162703, NULL, 0, 43.5386272, -84.0821024), 
	('Kansas City', 'MCI', 'MCI', 'KMCI', 'Kansas City International Airport', 'P-M', 5386242, 'DFW', 0, 39.2991181, -94.7107786), 
	('Macon', 'MCN', 'MCN', 'KMCN', 'Middle Georgia Regional Airport', 'P-N', 10029, NULL, 0, 32.7014571, -83.65010079999999), 
	('Orlando', 'MCO', 'MCO', 'KMCO', 'Orlando International Airport', 'P-L', 17288480, 'MIA', 0, 28.4311577, -81.308083), 
	('Mason City', 'MCW', 'MCW', 'KMCW', 'Mason City Municipal Airport', 'P-N', 11678, NULL, 0, 43.1531118, -93.3361585), 
	('Harrisburg/Middletown', 'MDT', 'MDT', 'KMDT', 'Harrisburg International Airport', 'P-S', 635627, 'ORD', 0, 40.1942375, -76.7576672), 
	('Meridian', 'MEI', 'MEI', 'KMEI', 'Meridian Regional Airport (Key Field)', 'P-N', 16871, NULL, 0, 32.333547, -88.7451526), 
	('Memphis', 'MEM', 'MEM', 'KMEM', 'Memphis International Airport', 'P-M', 5376818, 'ORD', 0, 35.0420679, -89.9791729), 
	('McAllen', 'MFE', 'MFE', 'KMFE', 'McAllen-Miller International Airport', 'P-N', 344302, NULL, 0, 26.1780926, -98.24103629999999), 
	('Medford', 'MFR', 'MFR', 'KMFR', 'Rogue Valley International-Medford Airport', 'P-N', 287688, NULL, 0, 42.3745323, -122.8738809), 
	('Montgomery', 'MGM', 'MGM', 'KMGM', 'Montgomery Regional Airport ("Dannelly Field")', 'P-N', 194540, NULL, 0, 32.3050713, -86.3906353), 
	('Manhattan', 'MHK', 'MHK', 'KMHK', 'Manhattan Regional Airport', 'P-N', 16489, NULL, 0, 39.1371223, -96.6699273), 
	('Manchester', 'MHT', 'MHT', 'KMHT', 'Manchester-Boston Regional Airport', 'P-M', 1834875, 'JFK', 0, 42.929687, -71.4352177), 
	('Miami', 'MIA', 'MIA', 'KMIA', 'Miami International Airport', 'P-L', 16377488, NULL, 1, 25.7958723, -80.2870509), 
	('Milwaukee', 'MKE', 'MKE', 'KMKE', 'General Mitchell International Airport', 'P-M', 3861333, 'ORD', 0, 42.9475534, -87.89664599999999), 
	('Muskegon', 'MKG', 'MKG', 'KMKG', 'Muskegon County Airport', 'P-N', 30051, NULL, 0, 43.16455209999999, -86.2380001), 
	('Kaunakakai', 'MKK', 'MKK', 'PHMK', 'Molokai Airport', 'P-N', 89468, NULL, 0, 21.1535674, -157.0963276), 
	('Melbourne', 'MLB', 'MLB', 'KMLB', 'Melbourne International Airport', 'P-N', 145117, NULL, 0, 28.1012659, -80.645078), 
	('Moline', 'MLI', 'MLI', 'KMLI', 'Quad City International Airport', 'P-S', 476532, 'ORD', 0, 39.2991181, -94.7107786), 
	('Monroe', 'MLU', 'MLU', 'KMLU', 'Monroe Regional Airport', 'P-N', 100419, NULL, 0, 32.51023110000001, -92.0436229), 
	('Mobile', 'MOB', 'MOB', 'KMOB', 'Mobile Regional Airport', 'P-N', 277232, NULL, 0, 30.692512, -88.24549359999999), 
	('Modesto', 'MOD', 'MOD', 'KMOD', 'Modesto City-County Airport (Harry Sham Field)', 'P-N', 37082, NULL, 0, 37.6269954, -120.9560394), 
	('Minot', 'MOT', 'MOT', 'KMOT', 'Minot International Airport', 'P-N', 71595, NULL, 0, 48.25567119999999, -101.2882265), 
	('Marquette/Gwinn', 'SAW', 'MQT', 'KSAW', 'Sawyer International Airport', 'P-N', 56172, NULL, 0, 46.7907719, -71.38856899999999), 
	('Anchorage', 'MRI', 'MRI', 'PAMR', 'Merrill Field', 'P-N', 15206, NULL, 0, 61.215917, -149.8419311), 
	('Monterey', 'MRY', 'MRY', 'KMRY', 'Monterey Peninsula Airport', 'P-N', 207964, NULL, 0, 36.5871457, -121.8462322), 
	('Madison', 'MSN', 'MSN', 'KMSN', 'Dane County Regional Airport (Truax Field)', 'P-S', 728075, 'JFK', 0, 43.1390659, -89.33641279999999), 
	('Missoula', 'MSO', 'MSO', 'KMSO', 'Missoula International Airport', 'P-N', 288071, NULL, 0, 46.9185943, -114.0858752), 
	('Minneapolis', 'MSP', 'MSP', 'KMSP', 'Minneapolis-St. Paul International Airport (Wold-Chamberlain Field)', 'P-L', 16369324, NULL, 0, 44.8847554, -93.2222846), 
	('New Orleans', 'MSY', 'MSY', 'KMSY', 'Louis Armstrong New Orleans International Airport', 'P-M', 4088037, 'DFW', 0, 29.9910905, -90.2592299), 
	('Montrose', 'MTJ', 'MTJ', 'KMTJ', 'Montrose Regional Airport', 'P-N', 85868, NULL, 0, 38.5002349, -107.8992134), 
	('Vineyard Haven', 'MVY', 'MVY', 'KMVY', 'Martha''s Vineyard Airport', 'P-N', 45002, NULL, 0, 41.388145, -70.613868), 
	('Myrtle Beach', 'MYR', 'MYR', 'KMYR', 'Myrtle Beach International Airport', 'P-S', 705430, 'ORD', 0, 33.6822019, -78.92789429999999), 
	('Jacksonville', 'OAJ', 'OAJ', 'KOAJ', 'Albert J. Ellis Airport', 'P-N', 126947, NULL, 0, 34.8291316, -77.60688429999999), 
	('Oakland', 'OAK', 'OAK', 'KOAK', 'Oakland International Airport', 'P-M', 5583748, 'LAX', 0, 37.7125689, -122.2197428), 
	('Kahului', 'OGG', 'OGG', 'PHOG', 'Kahului Airport', 'P-M', 2652335, 'MIA', 0, 20.8967924, -156.4329379), 
	('Oklahoma City', 'OKC', 'OKC', 'KOKC', 'Will Rogers World Airport', 'P-S', 1838709, 'ORD', 0, 35.393056, -97.600556), 
	('Omaha', 'OMA', 'OMA', 'KOMA', 'Eppley Airfield', 'P-M', 2083973, 'ORD', 0, 41.3018733, -95.8937409), 
	('Nome', 'OME', 'OME', 'PAOM', 'Nome Airport', 'P-N', 59984, NULL, 0, 64.5099347, -165.4435152), 
	('Ontario', 'ONT', 'ONT', 'KONT', 'Ontario International Airport', 'P-M', 2998110, 'LAX', 0, 34.0559781, -117.598057), 
	('Chicago', 'ORD', 'ORD', 'KORD', 'Chicago O''Hare International Airport', 'P-L', 33683991, NULL, 1, 41.9741625, -87.9073214), 
	('Norfolk', 'ORF', 'ORF', 'KORF', 'Norfolk International Airport', 'P-M', 1786594, 'ORD', 0, 36.8956837, -76.2000161), 
	('North Bend', 'OTH', 'OTH', 'KOTH', 'Southwest Oregon Regional Airport (was North Bend Municipal)', 'P-N', 35458, NULL, 0, 43.4162233, -124.2492439), 
	('Kotzebue', 'OTZ', 'OTZ', 'PAOT', 'Ralph Wien Memorial Airport', 'P-N', 66322, NULL, 0, 66.8913694, -162.6024888), 
	('Oxnard', 'OXR', 'OXR', 'KOXR', 'Oxnard Airport', 'P-N', 15961, NULL, 0, 34.1985056, -119.2065106), 
	('Paducah', 'PAH', 'PAH', 'KPAH', 'Barkley Regional Airport', 'P-N', 18452, NULL, 0, 37.0612439, -88.7675112), 
	('West Palm Beach', 'PBI', 'PBI', 'KPBI', 'Palm Beach International Airport', 'P-M', 3232009, 'MIA', 0, 26.6857475, -80.0928165), 
	('Portland', 'PDX', 'PDX', 'KPDX', 'Portland International Airport', 'P-M', 7090526, 'LAX', 0, 45.58976939999999, -122.5950942), 
	('Page', 'PGA', 'PGA', 'KPGA', 'Page Municipal Airport', 'P-N', 33118, NULL, 0, 36.9244374, -111.451092), 
	('Greenville', 'PGV', 'PGV', 'KPGV', 'Pitt-Greenville Airport', 'P-N', 52287, NULL, 0, 35.631926, -77.3798351), 
	('Newport News', 'PHF', 'PHF', 'KPHF', 'Newport News/Williamsburg International Airport', 'P-S', 504292, 'JFK', 0, 37.1307716, -76.4939006), 
	('Philadelphia', 'PHL', 'PHL', 'KPHL', 'Philadelphia International Airport', 'P-L', 15586852, 'JFK', 0, 39.8743959, -75.2424229), 
	('Phoenix', 'PHX', 'PHX', 'KPHX', 'Phoenix Sky Harbor International Airport', 'P-L', 19450576, 'DFW', 0, 33.4372686, -112.0077881), 
	('Hattiesburg/Laurel', 'PIB', 'PIB', 'KPIB', 'Hattiesburg-Laurel Regional Airport', 'P-N', 13766, NULL, 0, 31.468239, -89.335421), 
	('St. Petersburg', 'PIE', 'PIE', 'KPIE', 'St. Petersburg-Clearwater International Airport', 'P-N', 363725, NULL, 0, 27.9098674, -82.68885709999999), 
	('Pocatello/Arbon Valley', 'PIH', 'PIH', 'KPIH', 'Pocatello Regional Airport', 'P-N', 25756, NULL, 0, 42.9055766, -112.5886283), 
	('Pierre', 'PIR', 'PIR', 'KPIR', 'Pierre Regional Airport', 'P-N', 15983, NULL, 0, 44.3825, -100.285833), 
	('Pittsburgh', 'PIT', 'PIT', 'KPIT', 'Pittsburgh International Airport', 'P-M', 4292546, 'JFK', 0, 40.4919208, -80.2352233), 
	('Pellston', 'PLN', 'PLN', 'KPLN', 'Pellston Regional Airport of Emmet County', 'P-N', 26222, NULL, 0, 45.5714903, -84.78618340000001), 
	('Pensacola', 'PNS', 'PNS', 'KPNS', 'Pensacola Gulf Coast Regional Airport', 'P-S', 771917, 'MIA', 0, 30.4738158, -87.1867049), 
	('Presque Isle', 'PQI', 'PQI', 'KPQI', 'Northern Maine Regional Airport at Presque Isle', 'P-N', 13385, NULL, 0, 46.6860602, -68.0459444), 
	('Pasco', 'PSC', 'PSC', 'KPSC', 'Tri-Cities Airport', 'P-N', 242483, NULL, 0, 46.2631697, -119.1175903), 
	('Petersburg', 'PSG', 'PSG', 'PAPG', 'Petersburg James A. Johnson Airport', 'P-N', 19901, NULL, 0, 56.8016796, -132.9482065), 
	('Portsmouth', 'PSM', 'PSM', 'KPSM', 'Portsmouth International Airport at Pease', 'P-N', 49962, NULL, 0, 43.0802589, -70.8211285), 
	('Palm Springs', 'PSP', 'PSP', 'KPSP', 'Palm Springs International Airport', 'P-S', 772906, 'LAX', 0, 33.8303194, -116.5070468), 
	('Pullman/Moscow Idaho', 'PUW', 'PUW', 'KPUW', 'Pullman-Moscow Regional Airport', 'P-N', 32108, NULL, 0, 46.7441801, -117.1141262), 
	('Provincetown', 'PVC', 'PVC', 'KPVC', 'Provincetown Municipal Airport', 'P-N', 11468, NULL, 0, 42.072367, -70.222247), 
	('Providence/Warwick', 'PVD', 'PVD', 'KPVD', 'Theodore Francis Green State Airport', 'P-M', 2342593, 'JFK', 0, 41.7245271, -71.4304062), 
	('Portland', 'PWM', 'PWM', 'KPWM', 'Portland International Jetport', 'P-S', 876102, 'LAX', 0, 43.6464785, -70.30969739999999), 
	('Rapid City', 'RAP', 'RAP', 'KRAP', 'Rapid City Regional Airport', 'P-N', 273151, NULL, 0, 44.0383798, -103.0605163), 
	('Redding', 'RDD', 'RDD', 'KRDD', 'Redding Municipal Airport', 'P-N', 63331, NULL, 0, 40.5058184, -122.2996775), 
	('Redmond', 'RDM', 'RDM', 'KRDM', 'Redmond Municipal Airport (Roberts Field)', 'P-N', 235192, NULL, 0, 44.2532061, -121.1608592), 
	('Raleigh', 'RDU', 'RDU', 'KRDU', 'Raleigh-Durham International Airport', 'P-M', 4868492, 'JFK', 0, 35.88007899999999, -78.7879963), 
	('Rockford', 'RFD', 'RFD', 'KRFD', 'Chicago Rockford International Airport', 'P-N', 110151, NULL, 0, 42.20218029999999, -89.0988607), 
	('Rhinelander', 'RHI', 'RHI', 'KRHI', 'Rhinelander-Oneida County Airport', 'P-N', 26193, NULL, 0, 45.6262146, -89.463867), 
	('Richmond', 'RIC', 'RIC', 'KRIC', 'Richmond International Airport (Byrd Field)', 'P-S', 1733668, 'JFK', 0, 37.5065795, -77.3208112), 
	('Riverton', 'RIW', 'RIW', 'KRIW', 'Riverton Regional Airport', 'P-N', 17035, NULL, 0, 43.0613253, -108.4584185), 
	('Rockland', 'RKD', 'RKD', 'KRKD', 'Knox County Regional Airport', 'P-N', 13866, NULL, 0, 44.061802, -69.09430499999999), 
	('Rock Springs', 'RKS', 'RKS', 'KRKS', 'Southwest Wyoming Regional Airport', 'P-N', 25541, NULL, 0, 41.59746260000001, -109.0720642), 
	('Reno', 'RNO', 'RNO', 'KRNO', 'Reno-Tahoe International Airport', 'P-M', 2150816, 'ORD', 0, 39.4995907, -119.7680951), 
	('Roanoke', 'ROA', 'ROA', 'KROA', 'Roanoke Regional Airport (Woodrum Field)', 'P-N', 315293, NULL, 0, 37.320398, -79.9701915), 
	('Rochester', 'ROC', 'ROC', 'KROC', 'Greater Rochester International Airport', 'P-S', 1349694, 'JFK', 0, 43.1225229, -77.66657219999999), 
	('Rochester', 'RST', 'RST', 'KRST', 'Rochester International Airport', 'P-N', 151250, NULL, 0, 43.9109834, -92.4967704), 
	('Fort Myers', 'RSW', 'RSW', 'KRSW', 'Southwest Florida International Airport', 'P-M', 3770681, 'MIA', 0, 26.5337051, -81.7553083), 
	('San Diego', 'SAN', 'SAN', 'KSAN', 'San Diego International Airport', 'P-L', 9007617, 'LAX', 0, 32.7338006, -117.1933038), 
	('San Antonio', 'SAT', 'SAT', 'KSAT', 'San Antonio International Airport', 'P-M', 3916320, 'DWF', 0, 29.5311973, -98.4683484), 
	('Savannah', 'SAV', 'SAV', 'KSAV', 'Savannah/Hilton Head International Airport', 'P-S', 959037, 'MIA', 0, 32.1294267, -81.2018521), 
	('Santa Barbara', 'SBA', 'SBA', 'KSBA', 'Santa Barbara Municipal Airport', 'P-S', 413929, 'LAX', 0, 34.4271935, -119.8398835), 
	('South Bend', 'SBN', 'SBN', 'KSBN', 'South Bend Regional Airport', 'P-S', 357168, 'ORD', 0, 41.7077166, -86.315843), 
	('San Luis Obispo', 'SBP', 'SBP', 'KSBP', 'San Luis Obispo County Regional Airport (McChesney Field)', 'P-N', 150089, NULL, 0, 35.2374865, -120.6409032), 
	('Salisbury', 'SBY', 'SBY', 'KSBY', 'Salisbury-Ocean City Wicomico Regional Airport', 'P-N', 58863, NULL, 0, 38.34136710000001, -75.5131117), 
	('Deadhorse /Prudhoe Bay', 'SCC', 'SCC', 'PASC', 'Deadhorse Airport (Prudhoe Bay Airport)', 'P-N', 99719, NULL, 0, 70.1984121, -148.4611183), 
	('State College', 'UNV', 'SCE', 'KUNV', 'University Park Airport', 'P-N', 133777, NULL, 0, 40.8499873, -77.8486889), 
	('Stockton', 'SCK', 'SCK', 'KSCK', 'Stockton Metropolitan Airport', 'P-N', 36935, NULL, 0, 37.8968929, -121.2514811), 
	('Louisville', 'SDF', 'SDF', 'KSDF', 'Louisville International Airport (Standiford Field)', 'P-S', 1622804, 'MIA', 0, 38.175662, -85.7369231), 
	('Seattle/Tacoma (SeaTac)', 'SEA', 'SEA', 'KSEA', 'Seattle-Tacoma International Airport', 'P-L', 15839504, 'LAX', 0, 47.4502499, -122.3088165), 
	('Orlando', 'SFB', 'SFB', 'KSFB', 'Orlando Sanford International Airport', 'P-S', 927188, 'MIA', 0, 28.7793906, -81.2356859), 
	('San Francisco', 'SFO', 'SFO', 'KSFO', 'San Francisco International Airport', 'P-L', 18135827, 'LAX', 0, 37.6213129, -122.3789554), 
	('Springfield', 'SGF', 'SGF', 'KSGF', 'Springfield-Branson National Airport', 'P-S', 779995, 'MIA', 0, 37.244631, -93.39026559999999), 
	('Skagway', 'SGY', 'SGY', 'PAGY', 'Skagway Airport', 'P-N', 10727, NULL, 0, 59.4538434, -135.3264037), 
	('Sheridan', 'SHR', 'SHR', 'KSHR', 'Sheridan County Airport', 'P-N', 17710, NULL, 0, 44.7738565, -106.9705132), 
	('Shreveport', 'SHV', 'SHV', 'KSHV', 'Shreveport Regional Airport', 'P-N', 237945, NULL, 0, 32.4544911, -93.8286552), 
	('Sitka', 'SIT', 'SIT', 'PASI', 'Sitka Rocky Gutierrez Airport', 'P-N', 68197, NULL, 0, 57.0526917, -135.3653555), 
	('San Jose', 'SJC', 'SJC', 'KSJC', 'Norman Y. Mineta San Jose International Airport', 'P-M', 4780264, 'LAX', 0, 37.3639472, -121.9289375), 
	('San Angelo', 'SJT', 'SJT', 'KSJT', 'San Angelo Regional Airport (Mathis Field)', 'P-N', 56021, NULL, 0, 31.35728569999999, -100.5028459), 
	('Salt Lake City', 'SLC', 'SLC', 'KSLC', 'Salt Lake City International Airport', 'P-L', 9993198, 'DFW', 0, 40.7899404, -111.9790706), 
	('Sacramento', 'SMF', 'SMF', 'KSMF', 'Sacramento International Airport', 'P-M', 4986771, 'LAX', 0, 38.6950854, -121.5900648), 
	('Santa Maria', 'SMX', 'SMX', 'KSMX', 'Santa Maria Public Airport (Capt G. Allan Hancock Field)', 'P-N', 54925, NULL, 0, 34.8991556, -120.4478722), 
	('Santa Ana', 'SNA', 'SNA', 'KSNA', 'John Wayne Airport - Orange County (was Orange County Airport)', 'P-M', 4464380, 'LAX', 0, 33.6761901, -117.8674759), 
	('Springfield', 'SPI', 'SPI', 'KSPI', 'Abraham Lincoln Capital Airport', 'P-N', 56771, NULL, 0, 39.8439165, -89.6783951), 
	('Wichita Falls', 'SPS', 'SPS', 'KSPS', 'Wichita Falls Municipal Airport/Sheppard Air Force Base', 'P-N', 44296, NULL, 0, 33.9642825, -98.4918225), 
	('Sarasota/Bradenton', 'SRQ', 'SRQ', 'KSRQ', 'Sarasota-Bradenton International Airport', 'P-S', 753126, 'MIA', 0, 27.3951191, -82.55381969999999), 
	('St. Cloud', 'STC', 'STC', 'KSTC', 'St. Cloud Regional Airport', 'P-N', 20161, NULL, 0, 45.5479622, -94.06972329999999), 
	('St. Louis', 'STL', 'STL', 'KSTL', 'Lambert-St. Louis International Airport', 'P-M', 6740468, 'ORD', 0, 38.7499403, -90.374819), 
	('Santa Rosa', 'STS', 'STS', 'KSTS', 'Charles M. Schulz - Sonoma County Airport', 'P-N', 100676, NULL, 0, 38.5092305, -122.8132578), 
	('Hailey', 'SUN', 'SUN', 'KSUN', 'Friedman Memorial Airport', 'P-N', 64233, NULL, 0, 43.5066901, -114.2992901), 
	('Sioux City', 'SUX', 'SUX', 'KSUX', 'Sioux Gateway Airport (Col. Bud Day Field)', 'P-N', 49871, NULL, 0, 42.4053135, -96.3837817), 
	('Newburgh', 'SWF', 'SWF', 'KSWF', 'Stewart International Airport', 'P-N', 392464, NULL, 0, 41.4984032, -74.1008627), 
	('Syracuse', 'SYR', 'SYR', 'KSYR', 'Syracuse Hancock International Airport', 'P-S', 1105143, 'JFK', 0, 43.1139301, -76.1101888), 
	('Telluride', 'TEX', 'TEX', 'KTEX', 'Telluride Regional Airport', 'P-N', 13325, NULL, 0, 37.9545624, -107.9019696), 
	('Tallahassee', 'TLH', 'TLH', 'KTLH', 'Tallahassee Regional Airport', 'P-S', 399094, 'MIA', 0, 30.3954074, -84.3450518), 
	('Toledo', 'TOL', 'TOL', 'KTOL', 'Toledo Express Airport', 'P-N', 93669, NULL, 0, 41.5878083, -83.80914109999999), 
	('Tampa', 'TPA', 'TPA', 'KTPA', 'Tampa International Airport', 'P-L', 8871917, 'MIA', 0, 27.9771524, -82.5311382), 
	('Bristol Johnson City/Kingsport', 'TRI', 'TRI', 'KTRI', 'Tri-Cities Regional Airport (Tri-Cities Regional TN/VA)', 'P-N', 202730, NULL, 0, 36.4809142, -82.40839199999999), 
	('Tulsa', 'TUL', 'TUL', 'KTUL', 'Tulsa International Airport', 'P-S', 1606622, 'MIA', 0, 36.198778, -95.88386589999999), 
	('Tupelo', 'TUP', 'TUP', 'KTUP', 'Tupelo Regional Airport (C.D. Lemons Field)', 'P-N', 12749, NULL, 0, 34.2662432, -88.76633400000001), 
	('Tucson', 'TUS', 'TUS', 'KTUS', 'Tucson International Airport', 'P-M', 2070573, 'LAX', 0, 32.1145102, -110.9392269), 
	('Traverse City', 'TVC', 'TVC', 'KTVC', 'Cherry Capital Airport', 'P-N', 183357, NULL, 0, 44.7369137, -85.5796208), 
	('Twin Falls', 'TWF', 'TWF', 'KTWF', 'Magic Valley Regional Airport (Joslin Field)', 'P-N', 29606, NULL, 0, 42.4833496, -114.4847165), 
	('Texarkana', 'TXK', 'TXK', 'KTXK', 'Texarkana Regional Airport (Webb Field)', 'P-N', 29820, NULL, 0, 33.4568776, -93.9941485), 
	('Tyler', 'TYR', 'TYR', 'KTYR', 'Tyler Pounds Regional Airport', 'P-N', 74357, NULL, 0, 32.3511258, -95.40962929999999), 
	('Knoxville', 'TYS', 'TYS', 'KTYS', 'McGhee Tyson Airport', 'P-S', 839266, 'DFW', 0, 35.810833, -83.993889), 
	('Unalakleet', 'UNK', 'UNK', 'PAUN', 'Unalakleet Airport', 'P-N', 12327, NULL, 0, 63.8885069, -160.7993314), 
	('Tunica', 'UTA', 'UTM', 'KUTA', 'Tunica Municipal Airport', 'P-N', 65907, NULL, 0, 34.683299, -90.351412), 
	('Valdez', 'VDZ', 'VDZ', 'PAVD', 'Valdez Airport (Pioneer Field)', 'P-N', 14981, NULL, 0, 61.133889, -146.248333), 
	('North Las Vegas', 'VGT', 'VGT', 'KVGT', 'North Las Vegas Airport', 'P-N', 67389, NULL, 0, 36.2092336, -115.1994297), 
	('Valdosta', 'VLD', 'VLD', 'KVLD', 'Valdosta Regional Airport', 'P-N', 38269, NULL, 0, 30.7892346, -83.27882269999999), 
	('Valparaiso', 'VPS', 'VPS', 'KVPS', 'Northwest Florida Regional Airport/Eglin Air Force Base', 'P-N', 373808, NULL, 0, 30.49545509999999, -86.54984639999999), 
	('Wrangell', 'WRG', 'WRG', 'PAWG', 'Wrangell Airport', 'P-N', 10601, NULL, 0, 56.4850237, -132.3795998), 
	('Fayetteville', 'XNA', 'XNA', 'KXNA', 'Northwest Arkansas Regional Airport', 'P-S', 547871, 'ORD', 0, 36.2786587, -94.30429400000001), 
	('Yakutat', 'YAK', 'YAK', 'PAYA', 'Yakutat Airport', 'P-N', 11028, NULL, 0, 59.50942140000001, -139.6689486), 
	('Yakima', 'YKM', 'YKM', 'KYKM', 'Yakima Air Terminal (McAllister Field)', 'P-N', 69835, NULL, 0, 46.5702491, -120.4446481), 
	('Youngstown/Warren', 'YNG', 'YNG', 'KYNG', 'Youngstown-Warren Regional Airport/Youngstown ARS', 'P-N', 17391, NULL, 0, 41.2574658, -80.6671886), 
	('Yuma', 'NYL', 'YUM', 'KNYL', 'Yuma International Airport/MCAS Yuma', 'P-N', 87812, NULL, 0, 32.6685512, -114.5991383);

 * postgresql://gpadmin:***@ec2-35-178-108-225.eu-west-2.compute.amazonaws.com:5432/gpadmin
Done.
Done.
349 rows affected.

[]

### 2_Create_Time_Dim

##### Code to review

```%%sql
DROP TABLE IF EXISTS pricing.time_dim CASCADE;

CREATE TABLE pricing.time_dim (
	flight_date date,
	flight_month integer,
	flight_weekday integer,
	holiday_indicator integer
) DISTRIBUTED BY(flight_date);

INSERT INTO pricing.time_dim
SELECT dt
    , EXTRACT(MONTH FROM dt) AS flight_month
    , EXTRACT(DOW FROM dt) AS flight_weekday
    , CASE WHEN hol_date IS NULL THEN 0 ELSE 1 END AS holiday_indicator
FROM (SELECT dt::DATE
    FROM generate_series(DATE '2020-01-01', DATE '2022-12-31', INTERVAL '1 DAY') AS t(dt)) A
LEFT OUTER JOIN ( -- List of public holidays 2020-2022
    SELECT UNNEST('{"January 1, 2020",
    "January 20, 2020",
    "February 17, 2020",
    "May 25, 2020",
    "July 3, 2020",
    "July 4, 2020",
    "September 7, 2020",
    "October 12, 2020",
    "November 11, 2020",
    "November 26, 2020",
    "December 25, 2020",
    "January 1, 2021",
    "January 18, 2021",
    "February 15, 2021",
    "May 31, 2021",
    "July 4, 2021",
    "July 5, 2021",
    "September 6, 2021",
    "October 11, 2021",
    "November 11, 2021",
    "November 25, 2021",
    "December 24, 2021",
    "December 25, 2021",
    "December 31, 2021",
    "January 1, 2022",
    "January 17, 2022",
    "February 21, 2022",
    "May 30, 2022",
    "July 4, 2022",
    "September 5, 2022",
    "October 10, 2022",
    "November 11, 2022",
    "November 24, 2022",
    "December 25, 2022",
    "December 26, 2022"}'::DATE[]) hol_date) B
ON A.dt = B.hol_date;```

In [8]:
%%sql
DROP TABLE IF EXISTS pricing.time_dim CASCADE;

CREATE TABLE pricing.time_dim (
flight_date date,
flight_month integer,
flight_weekday integer,
holiday_indicator integer
)
DISTRIBUTED BY(flight_date);

INSERT INTO pricing.time_dim (flight_date, flight_month, flight_weekday, holiday_indicator) VALUES 
('1/1/10',1,6,1), 
('1/2/10',1,7,1), 
('1/3/10',1,1,1), 
('1/4/10',1,2,1), 
('1/5/10',1,3,0), 
('1/6/10',1,4,0), 
('1/7/10',1,5,0), 
('1/8/10',1,6,0), 
('1/9/10',1,7,0), 
('1/10/10',1,1,0), 
('1/11/10',1,2,0), 
('1/12/10',1,3,0), 
('1/13/10',1,4,0), 
('1/14/10',1,5,0), 
('1/15/10',1,6,0), 
('1/16/10',1,7,0), 
('1/17/10',1,1,0), 
('1/18/10',1,2,0), 
('1/19/10',1,3,0), 
('1/20/10',1,4,0), 
('1/21/10',1,5,0), 
('1/22/10',1,6,0), 
('1/23/10',1,7,0), 
('1/24/10',1,1,0), 
('1/25/10',1,2,0), 
('1/26/10',1,3,0), 
('1/27/10',1,4,0), 
('1/28/10',1,5,0), 
('1/29/10',1,6,0), 
('1/30/10',1,7,0), 
('1/31/10',1,1,0), 
('2/1/10',2,2,0), 
('2/2/10',2,3,0), 
('2/3/10',2,4,0), 
('2/4/10',2,5,0), 
('2/5/10',2,6,0), 
('2/6/10',2,7,0), 
('2/7/10',2,1,0), 
('2/8/10',2,2,0), 
('2/9/10',2,3,0), 
('2/10/10',2,4,0), 
('2/11/10',2,5,0), 
('2/12/10',2,6,0), 
('2/13/10',2,7,0), 
('2/14/10',2,1,0), 
('2/15/10',2,2,0), 
('2/16/10',2,3,0), 
('2/17/10',2,4,0), 
('2/18/10',2,5,0), 
('2/19/10',2,6,0), 
('2/20/10',2,7,0), 
('2/21/10',2,1,0), 
('2/22/10',2,2,0), 
('2/23/10',2,3,0), 
('2/24/10',2,4,0), 
('2/25/10',2,5,0), 
('2/26/10',2,6,0), 
('2/27/10',2,7,0), 
('2/28/10',2,1,0), 
('3/1/10',3,2,0), 
('3/2/10',3,3,0), 
('3/3/10',3,4,0), 
('3/4/10',3,5,0), 
('3/5/10',3,6,0), 
('3/6/10',3,7,0), 
('3/7/10',3,1,0), 
('3/8/10',3,2,0), 
('3/9/10',3,3,0), 
('3/10/10',3,4,0), 
('3/11/10',3,5,0), 
('3/12/10',3,6,0), 
('3/13/10',3,7,0), 
('3/14/10',3,1,0), 
('3/15/10',3,2,0), 
('3/16/10',3,3,0), 
('3/17/10',3,4,0), 
('3/18/10',3,5,0), 
('3/19/10',3,6,0), 
('3/20/10',3,7,0), 
('3/21/10',3,1,0), 
('3/22/10',3,2,0), 
('3/23/10',3,3,0), 
('3/24/10',3,4,0), 
('3/25/10',3,5,0), 
('3/26/10',3,6,0), 
('3/27/10',3,7,0), 
('3/28/10',3,1,0), 
('3/29/10',3,2,0), 
('3/30/10',3,3,0), 
('3/31/10',3,4,0), 
('4/1/10',4,5,0), 
('4/2/10',4,6,0), 
('4/3/10',4,7,0), 
('4/4/10',4,1,0), 
('4/5/10',4,2,0), 
('4/6/10',4,3,0), 
('4/7/10',4,4,0), 
('4/8/10',4,5,0), 
('4/9/10',4,6,0), 
('4/10/10',4,7,0), 
('4/11/10',4,1,0), 
('4/12/10',4,2,0), 
('4/13/10',4,3,0), 
('4/14/10',4,4,0), 
('4/15/10',4,5,0), 
('4/16/10',4,6,0), 
('4/17/10',4,7,0), 
('4/18/10',4,1,0), 
('4/19/10',4,2,0), 
('4/20/10',4,3,0), 
('4/21/10',4,4,0), 
('4/22/10',4,5,0), 
('4/23/10',4,6,0), 
('4/24/10',4,7,0), 
('4/25/10',4,1,0), 
('4/26/10',4,2,0), 
('4/27/10',4,3,0), 
('4/28/10',4,4,0), 
('4/29/10',4,5,0), 
('4/30/10',4,6,0), 
('5/1/10',5,7,0), 
('5/2/10',5,1,0), 
('5/3/10',5,2,0), 
('5/4/10',5,3,0), 
('5/5/10',5,4,0), 
('5/6/10',5,5,0), 
('5/7/10',5,6,0), 
('5/8/10',5,7,0), 
('5/9/10',5,1,0), 
('5/10/10',5,2,0), 
('5/11/10',5,3,0), 
('5/12/10',5,4,0), 
('5/13/10',5,5,0), 
('5/14/10',5,6,0), 
('5/15/10',5,7,0), 
('5/16/10',5,1,0), 
('5/17/10',5,2,0), 
('5/18/10',5,3,0), 
('5/19/10',5,4,0), 
('5/20/10',5,5,0), 
('5/21/10',5,6,0), 
('5/22/10',5,7,0), 
('5/23/10',5,1,0), 
('5/24/10',5,2,0), 
('5/25/10',5,3,0), 
('5/26/10',5,4,0), 
('5/27/10',5,5,0), 
('5/28/10',5,6,0), 
('5/29/10',5,7,0), 
('5/30/10',5,1,0), 
('5/31/10',5,2,0), 
('6/1/10',6,3,0), 
('6/2/10',6,4,0), 
('6/3/10',6,5,0), 
('6/4/10',6,6,0), 
('6/5/10',6,7,0), 
('6/6/10',6,1,0), 
('6/7/10',6,2,0), 
('6/8/10',6,3,0), 
('6/9/10',6,4,0), 
('6/10/10',6,5,0), 
('6/11/10',6,6,0), 
('6/12/10',6,7,0), 
('6/13/10',6,1,0), 
('6/14/10',6,2,0), 
('6/15/10',6,3,0), 
('6/16/10',6,4,0), 
('6/17/10',6,5,0), 
('6/18/10',6,6,0), 
('6/19/10',6,7,0), 
('6/20/10',6,1,0), 
('6/21/10',6,2,0), 
('6/22/10',6,3,0), 
('6/23/10',6,4,0), 
('6/24/10',6,5,0), 
('6/25/10',6,6,0), 
('6/26/10',6,7,0), 
('6/27/10',6,1,0), 
('6/28/10',6,2,0), 
('6/29/10',6,3,0), 
('6/30/10',6,4,1), 
('7/1/10',7,5,1), 
('7/2/10',7,6,1), 
('7/3/10',7,7,1), 
('7/4/10',7,1,1), 
('7/5/10',7,2,1), 
('7/6/10',7,3,1), 
('7/7/10',7,4,0), 
('7/8/10',7,5,0), 
('7/9/10',7,6,0), 
('7/10/10',7,7,0), 
('7/11/10',7,1,0), 
('7/12/10',7,2,0), 
('7/13/10',7,3,0), 
('7/14/10',7,4,0), 
('7/15/10',7,5,0), 
('7/16/10',7,6,0), 
('7/17/10',7,7,0), 
('7/18/10',7,1,0), 
('7/19/10',7,2,0), 
('7/20/10',7,3,0), 
('7/21/10',7,4,0), 
('7/22/10',7,5,0), 
('7/23/10',7,6,0), 
('7/24/10',7,7,0), 
('7/25/10',7,1,0), 
('7/26/10',7,2,0), 
('7/27/10',7,3,0), 
('7/28/10',7,4,0), 
('7/29/10',7,5,0), 
('7/30/10',7,6,0), 
('7/31/10',7,7,0), 
('8/1/10',8,1,0), 
('8/2/10',8,2,0), 
('8/3/10',8,3,0), 
('8/4/10',8,4,0), 
('8/5/10',8,5,0), 
('8/6/10',8,6,0), 
('8/7/10',8,7,0), 
('8/8/10',8,1,0), 
('8/9/10',8,2,0), 
('8/10/10',8,3,0), 
('8/11/10',8,4,0), 
('8/12/10',8,5,0), 
('8/13/10',8,6,0), 
('8/14/10',8,7,0), 
('8/15/10',8,1,0), 
('8/16/10',8,2,0), 
('8/17/10',8,3,0), 
('8/18/10',8,4,0), 
('8/19/10',8,5,0), 
('8/20/10',8,6,0), 
('8/21/10',8,7,0), 
('8/22/10',8,1,0), 
('8/23/10',8,2,0), 
('8/24/10',8,3,0), 
('8/25/10',8,4,0), 
('8/26/10',8,5,0), 
('8/27/10',8,6,0), 
('8/28/10',8,7,0), 
('8/29/10',8,1,0), 
('8/30/10',8,2,0), 
('8/31/10',8,3,0), 
('9/1/10',9,4,0), 
('9/2/10',9,5,0), 
('9/3/10',9,6,0), 
('9/4/10',9,7,0), 
('9/5/10',9,1,0), 
('9/6/10',9,2,0), 
('9/7/10',9,3,0), 
('9/8/10',9,4,0), 
('9/9/10',9,5,0), 
('9/10/10',9,6,0), 
('9/11/10',9,7,0), 
('9/12/10',9,1,0), 
('9/13/10',9,2,0), 
('9/14/10',9,3,0), 
('9/15/10',9,4,0), 
('9/16/10',9,5,0), 
('9/17/10',9,6,0), 
('9/18/10',9,7,0), 
('9/19/10',9,1,0), 
('9/20/10',9,2,0), 
('9/21/10',9,3,0), 
('9/22/10',9,4,0), 
('9/23/10',9,5,0), 
('9/24/10',9,6,0), 
('9/25/10',9,7,0), 
('9/26/10',9,1,0), 
('9/27/10',9,2,0), 
('9/28/10',9,3,0), 
('9/29/10',9,4,0), 
('9/30/10',9,5,0), 
('10/1/10',10,6,0), 
('10/2/10',10,7,0), 
('10/3/10',10,1,0), 
('10/4/10',10,2,0), 
('10/5/10',10,3,0), 
('10/6/10',10,4,0), 
('10/7/10',10,5,0), 
('10/8/10',10,6,0), 
('10/9/10',10,7,0), 
('10/10/10',10,1,0), 
('10/11/10',10,2,0), 
('10/12/10',10,3,0), 
('10/13/10',10,4,0), 
('10/14/10',10,5,0), 
('10/15/10',10,6,0), 
('10/16/10',10,7,0), 
('10/17/10',10,1,0), 
('10/18/10',10,2,0), 
('10/19/10',10,3,0), 
('10/20/10',10,4,0), 
('10/21/10',10,5,0), 
('10/22/10',10,6,0), 
('10/23/10',10,7,0), 
('10/24/10',10,1,0), 
('10/25/10',10,2,0), 
('10/26/10',10,3,0), 
('10/27/10',10,4,0), 
('10/28/10',10,5,0), 
('10/29/10',10,6,0), 
('10/30/10',10,7,0), 
('10/31/10',10,1,0), 
('11/1/10',11,2,0), 
('11/2/10',11,3,0), 
('11/3/10',11,4,0), 
('11/4/10',11,5,0), 
('11/5/10',11,6,0), 
('11/6/10',11,7,0), 
('11/7/10',11,1,0), 
('11/8/10',11,2,0), 
('11/9/10',11,3,0), 
('11/10/10',11,4,0), 
('11/11/10',11,5,0), 
('11/12/10',11,6,0), 
('11/13/10',11,7,0), 
('11/14/10',11,1,0), 
('11/15/10',11,2,0), 
('11/16/10',11,3,0), 
('11/17/10',11,4,0), 
('11/18/10',11,5,0), 
('11/19/10',11,6,0), 
('11/20/10',11,7,0), 
('11/21/10',11,1,0), 
('11/22/10',11,2,1), 
('11/23/10',11,3,1), 
('11/24/10',11,4,1), 
('11/25/10',11,5,1), 
('11/26/10',11,6,1), 
('11/27/10',11,7,1), 
('11/28/10',11,1,1), 
('11/29/10',11,2,1), 
('11/30/10',11,3,0), 
('12/1/10',12,4,0), 
('12/2/10',12,5,0), 
('12/3/10',12,6,0), 
('12/4/10',12,7,0), 
('12/5/10',12,1,0), 
('12/6/10',12,2,0), 
('12/7/10',12,3,0), 
('12/8/10',12,4,0), 
('12/9/10',12,5,0), 
('12/10/10',12,6,0), 
('12/11/10',12,7,0), 
('12/12/10',12,1,0), 
('12/13/10',12,2,0), 
('12/14/10',12,3,0), 
('12/15/10',12,4,0), 
('12/16/10',12,5,0), 
('12/17/10',12,6,0), 
('12/18/10',12,7,0), 
('12/19/10',12,1,0), 
('12/20/10',12,2,0), 
('12/21/10',12,3,0), 
('12/22/10',12,4,1), 
('12/23/10',12,5,1), 
('12/24/10',12,6,1), 
('12/25/10',12,7,1), 
('12/26/10',12,1,1), 
('12/27/10',12,2,1), 
('12/28/10',12,3,1), 
('12/29/10',12,4,1), 
('12/30/10',12,5,1), 
('12/31/10',12,6,1), 
('1/1/11',1,7,1), 
('1/2/11',1,1,1), 
('1/3/11',1,2,1), 
('1/4/11',1,3,0), 
('1/5/11',1,4,0), 
('1/6/11',1,5,0), 
('1/7/11',1,6,0), 
('1/8/11',1,7,0), 
('1/9/11',1,1,0), 
('1/10/11',1,2,0), 
('1/11/11',1,3,0), 
('1/12/11',1,4,0), 
('1/13/11',1,5,0), 
('1/14/11',1,6,0), 
('1/15/11',1,7,0), 
('1/16/11',1,1,0), 
('1/17/11',1,2,0), 
('1/18/11',1,3,0), 
('1/19/11',1,4,0), 
('1/20/11',1,5,0), 
('1/21/11',1,6,0), 
('1/22/11',1,7,0), 
('1/23/11',1,1,0), 
('1/24/11',1,2,0), 
('1/25/11',1,3,0), 
('1/26/11',1,4,0), 
('1/27/11',1,5,0), 
('1/28/11',1,6,0), 
('1/29/11',1,7,0), 
('1/30/11',1,1,0), 
('1/31/11',1,2,0), 
('2/1/11',2,3,0), 
('2/2/11',2,4,0), 
('2/3/11',2,5,0), 
('2/4/11',2,6,0), 
('2/5/11',2,7,0), 
('2/6/11',2,1,0), 
('2/7/11',2,2,0), 
('2/8/11',2,3,0), 
('2/9/11',2,4,0), 
('2/10/11',2,5,0), 
('2/11/11',2,6,0), 
('2/12/11',2,7,0), 
('2/13/11',2,1,0), 
('2/14/11',2,2,0), 
('2/15/11',2,3,0), 
('2/16/11',2,4,0), 
('2/17/11',2,5,0), 
('2/18/11',2,6,0), 
('2/19/11',2,7,0), 
('2/20/11',2,1,0), 
('2/21/11',2,2,0), 
('2/22/11',2,3,0), 
('2/23/11',2,4,0), 
('2/24/11',2,5,0), 
('2/25/11',2,6,0), 
('2/26/11',2,7,0), 
('2/27/11',2,1,0), 
('2/28/11',2,2,0), 
('3/1/11',3,3,0), 
('3/2/11',3,4,0), 
('3/3/11',3,5,0), 
('3/4/11',3,6,0), 
('3/5/11',3,7,0), 
('3/6/11',3,1,0), 
('3/7/11',3,2,0), 
('3/8/11',3,3,0), 
('3/9/11',3,4,0), 
('3/10/11',3,5,0), 
('3/11/11',3,6,0), 
('3/12/11',3,7,0), 
('3/13/11',3,1,0), 
('3/14/11',3,2,0), 
('3/15/11',3,3,0), 
('3/16/11',3,4,0), 
('3/17/11',3,5,0), 
('3/18/11',3,6,0), 
('3/19/11',3,7,0), 
('3/20/11',3,1,0), 
('3/21/11',3,2,0), 
('3/22/11',3,3,0), 
('3/23/11',3,4,0), 
('3/24/11',3,5,0), 
('3/25/11',3,6,0), 
('3/26/11',3,7,0), 
('3/27/11',3,1,0), 
('3/28/11',3,2,0), 
('3/29/11',3,3,0), 
('3/30/11',3,4,0), 
('3/31/11',3,5,0), 
('4/1/11',4,6,0), 
('4/2/11',4,7,0), 
('4/3/11',4,1,0), 
('4/4/11',4,2,0), 
('4/5/11',4,3,0), 
('4/6/11',4,4,0), 
('4/7/11',4,5,0), 
('4/8/11',4,6,0), 
('4/9/11',4,7,0), 
('4/10/11',4,1,0), 
('4/11/11',4,2,0), 
('4/12/11',4,3,0), 
('4/13/11',4,4,0), 
('4/14/11',4,5,0), 
('4/15/11',4,6,0), 
('4/16/11',4,7,0), 
('4/17/11',4,1,0), 
('4/18/11',4,2,0), 
('4/19/11',4,3,0), 
('4/20/11',4,4,0), 
('4/21/11',4,5,0), 
('4/22/11',4,6,0), 
('4/23/11',4,7,0), 
('4/24/11',4,1,0), 
('4/25/11',4,2,0), 
('4/26/11',4,3,0), 
('4/27/11',4,4,0), 
('4/28/11',4,5,0), 
('4/29/11',4,6,0), 
('4/30/11',4,7,0), 
('5/1/11',5,1,0), 
('5/2/11',5,2,0), 
('5/3/11',5,3,0), 
('5/4/11',5,4,0), 
('5/5/11',5,5,0), 
('5/6/11',5,6,0), 
('5/7/11',5,7,0), 
('5/8/11',5,1,0), 
('5/9/11',5,2,0), 
('5/10/11',5,3,0), 
('5/11/11',5,4,0), 
('5/12/11',5,5,0), 
('5/13/11',5,6,0), 
('5/14/11',5,7,0), 
('5/15/11',5,1,0), 
('5/16/11',5,2,0), 
('5/17/11',5,3,0), 
('5/18/11',5,4,0), 
('5/19/11',5,5,0), 
('5/20/11',5,6,0), 
('5/21/11',5,7,0), 
('5/22/11',5,1,0), 
('5/23/11',5,2,0), 
('5/24/11',5,3,0), 
('5/25/11',5,4,0), 
('5/26/11',5,5,0), 
('5/27/11',5,6,0), 
('5/28/11',5,7,0), 
('5/29/11',5,1,0), 
('5/30/11',5,2,0), 
('5/31/11',5,3,0), 
('6/1/11',6,4,0), 
('6/2/11',6,5,0), 
('6/3/11',6,6,0), 
('6/4/11',6,7,0), 
('6/5/11',6,1,0), 
('6/6/11',6,2,0), 
('6/7/11',6,3,0), 
('6/8/11',6,4,0), 
('6/9/11',6,5,0), 
('6/10/11',6,6,0), 
('6/11/11',6,7,0), 
('6/12/11',6,1,0), 
('6/13/11',6,2,0), 
('6/14/11',6,3,0), 
('6/15/11',6,4,0), 
('6/16/11',6,5,0), 
('6/17/11',6,6,0), 
('6/18/11',6,7,0), 
('6/19/11',6,1,0), 
('6/20/11',6,2,0), 
('6/21/11',6,3,0), 
('6/22/11',6,4,0), 
('6/23/11',6,5,0), 
('6/24/11',6,6,0), 
('6/25/11',6,7,0), 
('6/26/11',6,1,0), 
('6/27/11',6,2,0), 
('6/28/11',6,3,0), 
('6/29/11',6,4,0), 
('6/30/11',6,5,0), 
('7/1/11',7,6,0), 
('7/2/11',7,7,1), 
('7/3/11',7,1,1), 
('7/4/11',7,2,1), 
('7/5/11',7,3,1), 
('7/6/11',7,4,1), 
('7/7/11',7,5,1), 
('7/8/11',7,6,1), 
('7/9/11',7,7,1), 
('7/10/11',7,1,0), 
('7/11/11',7,2,0), 
('7/12/11',7,3,0), 
('7/13/11',7,4,0), 
('7/14/11',7,5,0), 
('7/15/11',7,6,0), 
('7/16/11',7,7,0), 
('7/17/11',7,1,0), 
('7/18/11',7,2,0), 
('7/19/11',7,3,0), 
('7/20/11',7,4,0), 
('7/21/11',7,5,0), 
('7/22/11',7,6,0), 
('7/23/11',7,7,0), 
('7/24/11',7,1,0), 
('7/25/11',7,2,0), 
('7/26/11',7,3,0), 
('7/27/11',7,4,0), 
('7/28/11',7,5,0), 
('7/29/11',7,6,0), 
('7/30/11',7,7,0), 
('7/31/11',7,1,0), 
('8/1/11',8,2,0), 
('8/2/11',8,3,0), 
('8/3/11',8,4,0), 
('8/4/11',8,5,0), 
('8/5/11',8,6,0), 
('8/6/11',8,7,0), 
('8/7/11',8,1,0), 
('8/8/11',8,2,0), 
('8/9/11',8,3,0), 
('8/10/11',8,4,0), 
('8/11/11',8,5,0), 
('8/12/11',8,6,0), 
('8/13/11',8,7,0), 
('8/14/11',8,1,0), 
('8/15/11',8,2,0), 
('8/16/11',8,3,0), 
('8/17/11',8,4,0), 
('8/18/11',8,5,0), 
('8/19/11',8,6,0), 
('8/20/11',8,7,0), 
('8/21/11',8,1,0), 
('8/22/11',8,2,0), 
('8/23/11',8,3,0), 
('8/24/11',8,4,0), 
('8/25/11',8,5,0), 
('8/26/11',8,6,0), 
('8/27/11',8,7,0), 
('8/28/11',8,1,0), 
('8/29/11',8,2,0), 
('8/30/11',8,3,0), 
('8/31/11',8,4,0), 
('9/1/11',9,5,0), 
('9/2/11',9,6,0), 
('9/3/11',9,7,0), 
('9/4/11',9,1,0), 
('9/5/11',9,2,0), 
('9/6/11',9,3,0), 
('9/7/11',9,4,0), 
('9/8/11',9,5,0), 
('9/9/11',9,6,0), 
('9/10/11',9,7,0), 
('9/11/11',9,1,0), 
('9/12/11',9,2,0), 
('9/13/11',9,3,0), 
('9/14/11',9,4,0), 
('9/15/11',9,5,0), 
('9/16/11',9,6,0), 
('9/17/11',9,7,0), 
('9/18/11',9,1,0), 
('9/19/11',9,2,0), 
('9/20/11',9,3,0), 
('9/21/11',9,4,0), 
('9/22/11',9,5,0), 
('9/23/11',9,6,0), 
('9/24/11',9,7,0), 
('9/25/11',9,1,0), 
('9/26/11',9,2,0), 
('9/27/11',9,3,0), 
('9/28/11',9,4,0), 
('9/29/11',9,5,0), 
('9/30/11',9,6,0), 
('10/1/11',10,7,0), 
('10/2/11',10,1,0), 
('10/3/11',10,2,0), 
('10/4/11',10,3,0), 
('10/5/11',10,4,0), 
('10/6/11',10,5,0), 
('10/7/11',10,6,0), 
('10/8/11',10,7,0), 
('10/9/11',10,1,0), 
('10/10/11',10,2,0), 
('10/11/11',10,3,0), 
('10/12/11',10,4,0), 
('10/13/11',10,5,0), 
('10/14/11',10,6,0), 
('10/15/11',10,7,0), 
('10/16/11',10,1,0), 
('10/17/11',10,2,0), 
('10/18/11',10,3,0), 
('10/19/11',10,4,0), 
('10/20/11',10,5,0), 
('10/21/11',10,6,0), 
('10/22/11',10,7,0), 
('10/23/11',10,1,0), 
('10/24/11',10,2,0), 
('10/25/11',10,3,0), 
('10/26/11',10,4,0), 
('10/27/11',10,5,0), 
('10/28/11',10,6,0), 
('10/29/11',10,7,0), 
('10/30/11',10,1,0), 
('10/31/11',10,2,0), 
('11/1/11',11,3,0), 
('11/2/11',11,4,0), 
('11/3/11',11,5,0), 
('11/4/11',11,6,0), 
('11/5/11',11,7,0), 
('11/6/11',11,1,0), 
('11/7/11',11,2,0), 
('11/8/11',11,3,0), 
('11/9/11',11,4,0), 
('11/10/11',11,5,0), 
('11/11/11',11,6,0), 
('11/12/11',11,7,0), 
('11/13/11',11,1,0), 
('11/14/11',11,2,0), 
('11/15/11',11,3,0), 
('11/16/11',11,4,0), 
('11/17/11',11,5,0), 
('11/18/11',11,6,0), 
('11/19/11',11,7,0), 
('11/20/11',11,1,0), 
('11/21/11',11,2,0), 
('11/22/11',11,3,0), 
('11/23/11',11,4,0), 
('11/24/11',11,5,1), 
('11/25/11',11,6,1), 
('11/26/11',11,7,1), 
('11/27/11',11,1,1), 
('11/28/11',11,2,1), 
('11/29/11',11,3,1), 
('11/30/11',11,4,0), 
('12/1/11',12,5,0), 
('12/2/11',12,6,0), 
('12/3/11',12,7,0), 
('12/4/11',12,1,0), 
('12/5/11',12,2,0), 
('12/6/11',12,3,0), 
('12/7/11',12,4,0), 
('12/8/11',12,5,0), 
('12/9/11',12,6,0), 
('12/10/11',12,7,0), 
('12/11/11',12,1,0), 
('12/12/11',12,2,0), 
('12/13/11',12,3,0), 
('12/14/11',12,4,0), 
('12/15/11',12,5,0), 
('12/16/11',12,6,0), 
('12/17/11',12,7,0), 
('12/18/11',12,1,0), 
('12/19/11',12,2,0), 
('12/20/11',12,3,0), 
('12/21/11',12,4,0), 
('12/22/11',12,5,0), 
('12/23/11',12,6,0), 
('12/24/11',12,7,1), 
('12/25/11',12,1,1), 
('12/26/11',12,2,1), 
('12/27/11',12,3,1), 
('12/28/11',12,4,1), 
('12/29/11',12,5,1), 
('12/30/11',12,6,1), 
('12/31/11',12,7,1), 
('1/1/12',1,1,1), 
('1/2/12',1,2,1), 
('1/3/12',1,3,0), 
('1/4/12',1,4,0), 
('1/5/12',1,5,0), 
('1/6/12',1,6,0), 
('1/7/12',1,7,0), 
('1/8/12',1,1,0), 
('1/9/12',1,2,0), 
('1/10/12',1,3,0), 
('1/11/12',1,4,0), 
('1/12/12',1,5,0), 
('1/13/12',1,6,0), 
('1/14/12',1,7,0), 
('1/15/12',1,1,0), 
('1/16/12',1,2,0), 
('1/17/12',1,3,0), 
('1/18/12',1,4,0), 
('1/19/12',1,5,0), 
('1/20/12',1,6,0), 
('1/21/12',1,7,0), 
('1/22/12',1,1,0), 
('1/23/12',1,2,0), 
('1/24/12',1,3,0), 
('1/25/12',1,4,0), 
('1/26/12',1,5,0), 
('1/27/12',1,6,0), 
('1/28/12',1,7,0), 
('1/29/12',1,1,0), 
('1/30/12',1,2,0), 
('1/31/12',1,3,0), 
('2/1/12',2,4,0), 
('2/2/12',2,5,0), 
('2/3/12',2,6,0), 
('2/4/12',2,7,0), 
('2/5/12',2,1,0), 
('2/6/12',2,2,0), 
('2/7/12',2,3,0), 
('2/8/12',2,4,0), 
('2/9/12',2,5,0), 
('2/10/12',2,6,0), 
('2/11/12',2,7,0), 
('2/12/12',2,1,0), 
('2/13/12',2,2,0), 
('2/14/12',2,3,0), 
('2/15/12',2,4,0), 
('2/16/12',2,5,0), 
('2/17/12',2,6,0), 
('2/18/12',2,7,0), 
('2/19/12',2,1,0), 
('2/20/12',2,2,0), 
('2/21/12',2,3,0), 
('2/22/12',2,4,0), 
('2/23/12',2,5,0), 
('2/24/12',2,6,0), 
('2/25/12',2,7,0), 
('2/26/12',2,1,0), 
('2/27/12',2,2,0), 
('2/28/12',2,3,0), 
('2/29/12',2,4,0), 
('3/1/12',3,5,0), 
('3/2/12',3,6,0), 
('3/3/12',3,7,0), 
('3/4/12',3,1,0), 
('3/5/12',3,2,0), 
('3/6/12',3,3,0), 
('3/7/12',3,4,0), 
('3/8/12',3,5,0), 
('3/9/12',3,6,0), 
('3/10/12',3,7,0), 
('3/11/12',3,1,0), 
('3/12/12',3,2,0), 
('3/13/12',3,3,0), 
('3/14/12',3,4,0), 
('3/15/12',3,5,0), 
('3/16/12',3,6,0), 
('3/17/12',3,7,0);

 * postgresql://gpadmin:***@ec2-35-178-108-225.eu-west-2.compute.amazonaws.com:5432/gpadmin
Done.
Done.
807 rows affected.

[]

### 3_Create_Routes

In [9]:
%%sql
DROP TABLE IF EXISTS pricing.routes CASCADE;

CREATE TABLE pricing.routes (
    ID SERIAL,
    Route_Type INTEGER,
    Origin VARCHAR(3),
    Destination VARCHAR(3),
    Hub VARCHAR(3)
    ) DISTRIBUTED BY (Origin, Destination);

-- all large and medium airport pairs have 1 connection flights

INSERT INTO pricing.routes
    (Route_Type, Origin, Destination, Hub)
SELECT 
    1, 
    t1.FAA, 
    t2.FAA,
    CASE WHEN RANDOM()<0.5 THEN t1.hub_assignment ELSE t2.hub_assignment END
FROM
    pricing.airports t1 
    JOIN pricing.airports t2 
        ON (t1.FAA <> t2.FAA)
WHERE
    t1.Airport_Role IN ('P-L','P-M') 
    AND t2.Airport_Role IN ('P-L','P-M')
    AND (t1.Is_Hub=0 
         AND t2.Is_Hub=0);

-- from all large sized airports to AA Hubs we have nonstop flights

INSERT INTO 
    pricing.routes (Route_Type, Origin, Destination, Hub)
SELECT 
    2, 
    t1.FAA, 
    t2.FAA, 
    NULL
FROM
    pricing.airports t1 
    JOIN pricing.airports t2 
        ON (t1.FAA <> t2.FAA)
WHERE
    t1.Airport_Role='P-L' 
    AND t2.Is_Hub=1;

-- from all AA Hubs we have nonstop flights to large airports

INSERT INTO 
    pricing.routes (Route_Type, Origin, Destination, Hub)
SELECT 
    3, 
    t1.FAA, 
    t2.FAA, 
    NULL
FROM
    pricing.airports t1 
    JOIN pricing.airports t2 
        ON (t1.FAA <> t2.FAA)
WHERE
    t1.Is_Hub=1 
    AND t2.Airport_Role='P-L';

-- from all medium sized airports to AA Hubs we have nonstop flights

INSERT INTO pricing.routes (Route_Type, Origin, Destination, Hub)
SELECT 4, t1.FAA, t2.FAA, NULL
FROM
pricing.airports t1 JOIN pricing.airports t2 ON (t1.FAA <> t2.FAA)
WHERE
t1.Airport_Role='P-M' AND t2.Is_Hub=1;


-- from all AA Hubs we have nonstop flights to medium airports

INSERT INTO pricing.routes (Route_Type, Origin, Destination, Hub)
SELECT 5, t1.FAA, t2.FAA, NULL
FROM
pricing.airports t1 JOIN pricing.airports t2 ON (t1.FAA <> t2.FAA)
WHERE
t1.Is_Hub=1 AND t2.Airport_Role='P-M';

 * postgresql://gpadmin:***@ec2-35-178-108-225.eu-west-2.compute.amazonaws.com:5432/gpadmin
Done.
Done.
3540 rows affected.
140 rows affected.
140 rows affected.
180 rows affected.
180 rows affected.

[]

### 4_Create_Flights

In [10]:
%%sql
DROP TABLE IF EXISTS pricing.flight_times CASCADE;

CREATE TABLE pricing.flight_times AS
SELECT 'AA'||to_char(row_number() OVER (ORDER BY RANDOM(), Origin, Destination, DayPart), '00000') AS flight_number, 
r.Route_Type, Origin, Destination, DayPart
FROM
pricing.routes r,
(SELECT UNNEST(ARRAY[1,1,1,1,0]) as freq_2, 
		UNNEST(ARRAY[0,1,1,1,1]) as freq_3,
		UNNEST(ARRAY[1,1,1,0,0]) as freq_4,
		UNNEST(ARRAY[0,0,1,1,1]) as freq_5,
		UNNEST(ARRAY['Early-Morning', 'Morning', 'Afternoon', 'Evening', 'Late Evening']) AS daypart) dp 
WHERE r.route_type IN (2,3,4,5) 
AND ( (route_type=2 AND freq_2=1) OR (route_type=3 AND freq_3=1)  OR (route_type=4 AND freq_4=1) OR (route_type=5 AND freq_5=1))
DISTRIBUTED BY (flight_number);

DROP TABLE IF EXISTS pricing.flight_capacities CASCADE;

CREATE TABLE pricing.flight_capacities AS
SELECT Flight_Number, Class,
CASE WHEN r.route_type IN (2,3) and class='Economy' THEN 195
WHEN r.route_type IN (2,3) and class='Business' THEN 15
WHEN r.route_type IN (2,3) and class='First-Class' THEN 15
WHEN r.route_type IN (4,5) and class='Economy' THEN 128
WHEN r.route_type IN (4,5) and class='Business' THEN 30
WHEN r.route_type IN (4,5) and class='First-Class' THEN 10 END as Capacity
FROM
pricing.flight_times r,
(SELECT UNNEST(ARRAY['Economy', 'Business', 'First-Class']) as class) cl
DISTRIBUTED BY (flight_number);

DROP SEQUENCE IF EXISTS route_serial CASCADE;
CREATE SEQUENCE route_serial START 101;

DROP TABLE IF EXISTS pricing.route_flight_assignment CASCADE;
CREATE TABLE pricing.route_flight_assignment AS
SELECT 
nextval('route_serial') as routeID,
r.origin as Route_Origin, r.destination as Route_Destination, fl.flight_number as First_Flight_Number, fl.origin as First_Origin, fl.destination as First_Destination, fl.daypart as First_DayPart, NULL as Second_Flight_Number, NULL as Second_Origin, NULL as Second_Destination, NULL as Second_DayPart
FROM
pricing.routes r,
pricing.flight_times fl
WHERE
r.origin=fl.origin AND
r.destination=fl.destination AND
r.route_type>1
UNION ALL
SELECT 
nextval('route_serial'),
r.origin, r.destination, fl1.flight_number, fl1.origin, fl1.destination, fl1.daypart, fl2.flight_number, fl2.origin, fl2.destination, fl2.daypart
FROM
pricing.routes r,
pricing.flight_times fl1,
pricing.flight_times fl2
WHERE
r.route_type=1 AND r.origin=fl1.origin AND fl1.destination=r.hub AND
fl2.origin= r. hub AND fl2.destination = r.destination 
AND
((fl2.daypart='Morning' AND fl1.daypart='Early Morning')  OR 
 (fl2.daypart='Afternoon' AND fl1.daypart='Morning') OR
 (fl2.daypart='Evening' AND fl1.daypart='Afternoon') OR
 (fl2.daypart='Late Evening' AND fl1.daypart='Evening') )
DISTRIBUTED BY (Route_Origin, Route_Destination);

 * postgresql://gpadmin:***@ec2-35-178-108-225.eu-west-2.compute.amazonaws.com:5432/gpadmin
Done.
2200 rows affected.
Done.
6600 rows affected.
Done.
Done.
Done.
10429 rows affected.

[]

### 5_Create_Sales_History

In [11]:
%%sql

DROP TABLE IF EXISTS pricing.flight_history_staging CASCADE;

CREATE TABLE pricing.flight_history_staging (
RouteID BIGINT, --INTEGER, (type changed to match other tables)
Origin VARCHAR(3),
Destination VARCHAR(3),
Flight_1 VARCHAR(10),
Flight_2 VARCHAR(10),
Class TEXT,
Days_To_Flight INTEGER,
Flight_Date DATE,
Flight_Month INTEGER,
Flight_Weekday INTEGER,
holiday_indicator INTEGER,
Price DOUBLE PRECISION,
Price_Comp1 DOUBLE PRECISION,
Price_Comp2 DOUBLE PRECISION,
Price_Comp3 DOUBLE PRECISION,
Price_Comp4 DOUBLE PRECISION
)
DISTRIBUTED BY (RouteID);


INSERT INTO pricing.flight_history_staging
SELECT
routeID,
route_origin,
route_destination,
first_flight_number,
second_flight_number,
class,
Days_To_Flight,
flight_date,
flight_month,
flight_weekday,
holiday_indicator,
CASE WHEN Class='Economy' THEN
		CASE WHEN (Days_To_Flight<5) THEN 300+500*RANDOM()
	 		 WHEN (Days_To_Flight<10) THEN 200+400*RANDOM()
	 		 ELSE  100+300*RANDOM() END
	 WHEN Class='Business' THEN
		CASE WHEN (Days_To_Flight<5) THEN 800+500*RANDOM()
	 		 WHEN (Days_To_Flight<10) THEN 700+400*RANDOM()
	 		 ELSE  600+300*RANDOM() END
	  WHEN Class='First-Class' THEN
		CASE WHEN (Days_To_Flight<5) THEN 2000+500*RANDOM()
	 		 WHEN (Days_To_Flight<10) THEN 1200+400*RANDOM()
	 		 ELSE  1000+300*RANDOM() END
END	 as Price,
CASE WHEN Class='Economy' THEN
		CASE WHEN (Days_To_Flight<5) THEN 350+500*RANDOM()
	 		 WHEN (Days_To_Flight<10) THEN 250+400*RANDOM()
	 		 ELSE  100+300*RANDOM() END
	 WHEN Class='Business' THEN
		CASE WHEN (Days_To_Flight<5) THEN 800+500*RANDOM()
	 		 WHEN (Days_To_Flight<10) THEN 700+400*RANDOM()
	 		 ELSE  600+300*RANDOM() END
	  WHEN Class='First-Class' THEN
		CASE WHEN (Days_To_Flight<5) THEN 2100+500*RANDOM()
	 		 WHEN (Days_To_Flight<10) THEN 1500+400*RANDOM()
	 		 ELSE  1000+300*RANDOM() END
END	 as Price_Comp1,
CASE WHEN Class='Economy' THEN
		CASE WHEN (Days_To_Flight<5) THEN 300+500*RANDOM()
	 		 WHEN (Days_To_Flight<10) THEN 200+400*RANDOM()
	 		 ELSE  100+300*RANDOM() END
	 WHEN Class='Business' THEN
		CASE WHEN (Days_To_Flight<5) THEN 700+500*RANDOM()
	 		 WHEN (Days_To_Flight<10) THEN 600+400*RANDOM()
	 		 ELSE  500+300*RANDOM() END
	  WHEN Class='First-Class' THEN
		CASE WHEN (Days_To_Flight<5) THEN 900+500*RANDOM()
	 		 WHEN (Days_To_Flight<10) THEN 800+400*RANDOM()
	 		 ELSE  700+300*RANDOM() END
END	 as Price_Comp2,
CASE WHEN Class='Economy' THEN
		CASE WHEN (Days_To_Flight<5) THEN 200+300*RANDOM()
	 		 WHEN (Days_To_Flight<10) THEN 200+200*RANDOM()
	 		 ELSE  200+100*RANDOM() END
	 WHEN Class='Business' THEN
		CASE WHEN (Days_To_Flight<5) THEN 400+200*RANDOM()
	 		 WHEN (Days_To_Flight<10) THEN 300+200*RANDOM()
	 		 ELSE  300+200*RANDOM() END
	  WHEN Class='First-Class' THEN
		CASE WHEN (Days_To_Flight<5) THEN 500+200*RANDOM()
	 		 WHEN (Days_To_Flight<10) THEN 400+200*RANDOM()
	 		 ELSE  300+200*RANDOM() END
END	 as Price_Comp3,
CASE WHEN Class='Economy' THEN
		CASE WHEN (Days_To_Flight<5) THEN 250+200*RANDOM()
	 		 WHEN (Days_To_Flight<10) THEN 200+300*RANDOM()
	 		 ELSE  100+100*RANDOM() END
	 WHEN Class='Business' THEN
		CASE WHEN (Days_To_Flight<5) THEN 350+200*RANDOM()
	 		 WHEN (Days_To_Flight<10) THEN 250+200*RANDOM()
	 		 ELSE  150+200*RANDOM() END
	  WHEN Class='First-Class' THEN
		CASE WHEN (Days_To_Flight<5) THEN 350+200*RANDOM()
	 		 WHEN (Days_To_Flight<10) THEN 250+200*RANDOM()
	 		 ELSE  150+200*RANDOM() END
END	 as Price_Comp4
FROM
pricing.route_flight_assignment route, 
(SELECT generate_series(1,14:: bigint) as Days_To_Flight) days,
(SELECT * FROM pricing.time_dim WHERE flight_date<current_date) tt,
(SELECT UNNEST(ARRAY['Economy', 'Business', 'First-Class']) as class) cl;

 * postgresql://gpadmin:***@ec2-35-178-108-225.eu-west-2.compute.amazonaws.com:5432/gpadmin
Done.
Done.
353480526 rows affected.

[]

### 6_Create_Sales_History_Cont

In [12]:
%%sql
/*
 * Revised version using SQL as opposed to a function
 * 16 April 2015
 * Alastair Turner, Pivotal
 */

CREATE OR REPLACE FUNCTION pricing.bounded_random (lower_bound float8, upper_bound float8)
RETURNS float8
AS
$functionBody$
  SELECT $1 + ($2 - $1) * RANDOM();
$functionBody$
LANGUAGE SQL;


DROP TABLE IF EXISTS pricing.flight_history;
CREATE TABLE pricing.flight_history (
  RouteID BIGINT, --INTEGER, (type changed to match other tables)
  Origin VARCHAR(3),
  Destination VARCHAR(3),
  Flight_1 VARCHAR(10),
  Flight_2 VARCHAR(10),
  Class TEXT,
  Days_To_Flight INTEGER,
  Flight_Date DATE,
  Flight_Month INTEGER,
  Flight_Weekday INTEGER,
  holiday_indicator INTEGER,
  Price DOUBLE PRECISION,
  Price_Comp1 DOUBLE PRECISION,
  Price_Comp2 DOUBLE PRECISION,
  Price_Comp3 DOUBLE PRECISION,
  Price_Comp4 DOUBLE PRECISION,
  Sales INTEGER
)
DISTRIBUTED BY (RouteID);

INSERT INTO pricing.flight_history
--First pass determines advance booking category and capacity for the route
WITH first_pass AS (
  SELECT *,
      CASE WHEN days_to_flight > 3 THEN TRUNC(days_to_flight/5) + 1 ELSE 3 END AS advance_category,
      CASE WHEN class = 'Economy' THEN 198 WHEN class = 'Business' THEN 30 ELSE 20 END AS capacity
    FROM pricing.flight_history_staging    gfds
),
--Now that we have some basic values to work with get the max price and build the price comparison factors,
--  holiday factor and weekday factor
second_pass AS (
  SELECT *,
      --Maximum price (this really isn't pretty :( )
      CASE
        WHEN (class = 'Economy' AND advance_category = 1) THEN 800
        WHEN (class = 'Economy' AND advance_category = 2) THEN 600
        WHEN (class = 'Economy' AND advance_category = 3) THEN 400
        WHEN (class = 'Business' AND advance_category = 1) THEN 1300
        WHEN (class = 'Business' AND advance_category = 2) THEN 1100
        WHEN (class = 'Business' AND advance_category = 3) THEN 900
        WHEN (class NOT IN('Business', 'Economy') AND advance_category = 1) THEN 2500
        WHEN (class NOT IN('Business', 'Economy') AND advance_category = 2) THEN 1600
        WHEN (class NOT IN('Business', 'Economy') AND advance_category = 3) THEN 1300
      END AS max_price,
      --Price comparison factors
      CASE WHEN price_comp1 - price < -20 THEN pricing.bounded_random(.85, .95) ELSE 1 END AS comp1_factor,
      CASE WHEN price_comp2 - price < -20 THEN pricing.bounded_random(.7, 1)  ELSE 1 END AS comp2_factor,
      CASE WHEN price_comp3 - price < 40 THEN pricing.bounded_random(.8, .95) ELSE 1 END AS comp3_factor,
      CASE WHEN price_comp4 - price < -60 THEN pricing.bounded_random(.95 , 1) ELSE 1 END AS comp4_factor,
      --Holiday factor
      CASE
        WHEN (holiday_indicator = 1 AND class = 'Economy') THEN pricing.bounded_random(1.4, 1.6)
        WHEN (holiday_indicator = 1 AND class <> 'Economy') THEN pricing.bounded_random(.7, .9)
        ELSE 1
      END AS holiday_factor,
      --Day of week factor
      CASE
        WHEN (class='Economy' AND flight_weekday IN (1, 6, 7)) THEN pricing.bounded_random(1.2, 1.4)
        WHEN (class='Economy' AND flight_weekday NOT IN (1, 6, 7)) THEN pricing.bounded_random(.8, 1)
        WHEN (class<>'Economy' AND flight_weekday IN (2, 5, 6)) THEN pricing.bounded_random(1.3, 1.5)
        WHEN (class<>'Economy' AND flight_weekday NOT IN (2, 5, 6)) THEN pricing.bounded_random(.8, .9)
        ELSE 1
      END AS weekday_factor
    FROM first_pass
),
--The only item remaining is the price factor
third_pass AS (
  SELECT *,
      8 - (price/max_price) AS price_factor
  FROM second_pass
)
SELECT
    RouteID, Origin, Destination, Flight_1, Flight_2, Class, Days_To_Flight, Flight_Date, Flight_Month, Flight_Weekday,
    holiday_indicator, Price, Price_Comp1, Price_Comp2, Price_Comp3, Price_Comp4,
    TRUNC(capacity / 20 * comp1_factor * comp2_factor * comp3_factor * comp4_factor * holiday_factor * weekday_factor * price_factor) AS sales
  FROM third_pass;

 * postgresql://gpadmin:***@ec2-35-178-108-225.eu-west-2.compute.amazonaws.com:5432/gpadmin
Done.
Done.
Done.
353480526 rows affected.

[]

### 7_Routes_To_Be_Priced

In [13]:
%%sql
--Scoring
DROP TABLE IF EXISTS pricing.to_be_priced_flights CASCADE;

CREATE TABLE pricing.to_be_priced_flights AS
--SELECT
--    routeID
--    , route_origin
--    , route_destination
--    , first_flight_number
--    , second_flight_number
--    , CLASS
--    , Days_To_Flight
--    , flight_date
--    , flight_month
--    , flight_weekday
--    , holiday_indicator
--    , 0.0::DOUBLE PRECISION AS Price_Comp1
--    , 0.0::DOUBLE PRECISION AS Price_Comp2
--    , 0.0::DOUBLE PRECISION AS Price_Comp3
--    , 0.0::DOUBLE PRECISION AS Price_Comp4
--FROM
--    pricing.route_flight_assignment route
--    , (SELECT GENERATE_SERIES(1, 14:: INTEGER) AS Days_To_Flight) days
--    , (SELECT * FROM pricing.time_dim WHERE flight_date>'2011-10-31') tt
--    , (SELECT UNNEST(ARRAY['Economy', 'Business', 'First-Class']) AS class) cl
SELECT 
    routeid 
    , origin AS route_origin 
    , destination AS route_destination 
    , flight_1 AS first_flight_number 
    , flight_2 AS second_flight_number 
    , class 
    , days_to_flight 
    , flight_date 
    , flight_month 
    , flight_weekday 
    , holiday_indicator 
    , price_comp1 
    , price_comp2 
    , price_comp3 
    , price_comp4 
FROM 
    pricing.flight_history fh 
WHERE 
    flight_date>'2011-10-31' 
DISTRIBUTED BY (routeID);

 * postgresql://gpadmin:***@ec2-35-178-108-225.eu-west-2.compute.amazonaws.com:5432/gpadmin
Done.
60446484 rows affected.

[]

In [14]:
%%sql
SELECT * FROM pricing.routes
WHERE origin = 'LAX'
    AND destination = 'JFK';

 * postgresql://gpadmin:***@ec2-35-178-108-225.eu-west-2.compute.amazonaws.com:5432/gpadmin
2 rows affected.

[(3635, 2, 'LAX', 'JFK', None), (3809, 3, 'LAX', 'JFK', None)]